--- AUTO GENERATED OUTPUT from Ghidra script "ari-asstring-extractor.py" on 2021-04-23_15:57:59 
return {
    ["IBIAccFreqReportingType"] = {
        [0] = "IBI_FREQ_REPORTING_SINGLE_SHOT",
        [1] = "IBI_FREQ_REPORTING_CONTINEOUS",
        [2] = "IBI_FREQ_REPORTING_STOP",
    },
    ["IBIApacsType"] = {
        [0] = "ICE_IBI_APACS_MCC",
        [1] = "ICE_IBI_APACS_PLMN",
        [2] = "ICE_IBI_APACS_CELL",
        [3] = "ICE_IBI_APACS_BORDER",
        [4] = "ICE_IBI_APACS_PUSH",
    },
    ["IBIApacs_status_resp"] = {
        [0] = "APACS_STATUS_NO_HITS_IN_DB",
        [1] = "APACS_STATUS_LOCATION_SERVICES_NOT_AVAILABLE",
        [2] = "APACS_STATUS_LOCATION_SERVICES_AVAILABLE_NOW",
        [3] = "APACS_STATUS_PLMN_NOT_FOUND_IN_DB",
        [4] = "APACS_STATUS_NEW_APACS_DATA_DB_AVAILABLE_NOW",
        [5] = "APACS_STATUS_LOCATION_CANNOT_BE_DETERMINED",
    },
    ["IBICallCsAlertPitch"] = {
        [0] = "IBI_CALL_CS_SIGNAL_PITCH_MED",
        [1] = "IBI_CALL_CS_SIGNAL_PITCH_HIGH",
        [2] = "IBI_CALL_CS_SIGNAL_PITCH_LOW",
        [3] = "IBI_CALL_CS_SIGNAL_PITCH_RESERVED",
    },
    ["IBICallCsBurstDtmfEvent"] = {
        [0] = "IBI_CALL_CS_DTMF_EVENT_SEND_BURST",
        [1] = "IBI_CALL_CS_DTMF_EVENT_SEND_START_CONTINUOUS",
        [2] = "IBI_CALL_CS_DTMF_EVENT_SEND_STOP_CONTINUOUS",
        [3] = "IBI_CALL_CS_DTMF_EVENT_RCV_BURST",
        [4] = "IBI_CALL_CS_DTMF_EVENT_RCV_START_CONTINUOUS",
        [5] = "IBI_CALL_CS_DTMF_EVENT_RCV_STOP_CONTINUOUS",
    },
    ["IBICallCsBurstDtmfInterval"] = {
        [0] = "IBI_CALL_CS_BURST_DTMF_INTERVAL_60MS",
        [1] = "IBI_CALL_CS_BURST_DTMF_INTERVAL_100MS",
        [2] = "IBI_CALL_CS_BURST_DTMF_INTERVAL_150MS",
        [3] = "IBI_CALL_CS_BURST_DTMF_INTERVAL_200MS",
    },
    ["IBICallCsBurstDtmfWidth"] = {
        [0] = "IBI_CALL_CS_BURST_DTMF_WIDTH_95MS",
        [1] = "IBI_CALL_CS_BURST_DTMF_WIDTH_150MS",
        [2] = "IBI_CALL_CS_BURST_DTMF_WIDTH_200MS",
        [3] = "IBI_CALL_CS_BURST_DTMF_WIDTH_250MS",
        [4] = "IBI_CALL_CS_BURST_DTMF_WIDTH_300MS",
        [5] = "IBI_CALL_CS_BURST_DTMF_WIDTH_350MS",
        [6] = "IBI_CALL_CS_BURST_DTMF_WIDTH_SMS",
    },
    ["IBICallCsCdmaVerifySpcCodeResult"] = {
        [0] = "IBI_CALL_CS_CDMA_SPC_VALIDATION_SUCCESSFUL",
        [1] = "IBI_CALL_CS_CDMA_SPC_VALIDATION_FAILED_MAX_ATTEMPTS_NOT_REACHED",
        [2] = "IBI_CALL_CS_CDMA_SPC_VALIDATION_FAILED_MAX_ATTEMPTS_REACHED",
    },
    ["IBICallCsClirCause"] = {
        [0] = "IBI_CALL_CS_CLI_AVAILABLE",
        [1] = "IBI_CALL_CS_CLI_RESTRICTED",
        [2] = "IBI_CALL_CS_CLI_NOT_AVAILABLE",
        [3] = "IBI_CALL_CS_CLIR_OVERRIDE",
    },
    ["IBICallCsClirMode"] = {
        [0] = "IBI_CALL_CS_USE_DEFAULT",
        [1] = "IBI_CALL_CS_DISPLAY_PHONE_NUMBER",
        [2] = "IBI_CALL_CS_SUPPRESS_PHONE_NUMBER",
    },
    ["IBICallCsCmd"] = {
        [0] = "IBI_CALL_CS_CMD_SET",
        [1] = "IBI_CALL_CS_CMD_GET",
    },
    ["IBICallCsCrssGroup"] = {
        [0] = "IBI_CALL_CS_HOLD_ACTIVE_ACCEPT_WAITING",
    },
    ["IBICallCsDualServiceMode"] = {
        [0] = "IBI_CALL_CS_DUAL_BS61",
        [1] = "IBI_CALL_CS_DUAL_BS81",
        [2] = "IBI_CALL_CS_DUAL_FALLBACK",
        [3] = "IBI_CALL_CS_DUAL_TS61",
    },
    ["IBICallCsEmergencyCallIntermediateStatus"] = {
        [0] = "IBI_CALL_CS_ECALL_INTERMEDIATE_STATUS_SCAN_IN_PROGRESS",
        [1] = "IBI_CALL_CS_ECALL_INTERMEDIATE_STATUS_REDIAL_IN_PROGRESS",
        [2] = "IBI_CALL_CS_ECALL_INTERMEDIATE_STATUS_LOWER_LAYER_FAILURE",
        [3] = "IBI_CALL_CS_ECALL_INTERMEDIATE_STATUS_LTE_ONLY_AVAILABLE",
    },
    ["IBICallCsFeat"] = {
        [0] = "IBI_CALL_CS_FEAT_DISABLE",
        [1] = "IBI_CALL_CS_FEAT_ENABLE",
        [2] = "IBI_CALL_CS_FEAT_NO_CHANGE",
    },
    ["IBICallCsGroup"] = {
        [0] = "IBI_CALL_CS_DESIGNATED_CALL",
        [1] = "IBI_CALL_CS_ALL_CALLS",
        [2] = "IBI_CALL_CS_ALL_ACTIVE_CALLS",
        [3] = "IBI_CALL_CS_ALL_ACTIVE_AND_HELD_CALLS",
        [4] = "IBI_CALL_CS_ALL_IN_MPTY",
        [5] = "IBI_CALL_CS_ALL_HELD_CALLS",
        [6] = "IBI_CALL_CS_ALL_HELD_CALLS_NO_UDUB",
        [7] = "IBI_CALL_CS_ALL_ACTIVE_ACCEPT_WAITING",
    },
    ["IBICallCsLine"] = {
        [1] = "IBI_CALL_CS_LINE_2",
        [0] = "IBI_CALL_CS_LINE_1",
    },
    ["IBICallCsResult"] = {
        [0] = "IBI_CALL_CS_SUCCESS",
        [98] = "IBI_CALL_CS_CALL_ERROR",
        [99] = "IBI_CALL_CS_UNKNOWN",
    },
    ["IBICallCsSignalType"] = {
        [0] = "IBI_CALL_CS_SIGNAL_TYPE_TONE",
        [1] = "IBI_CALL_CS_SIGNAL_TYPE_ISDN_ALERT",
        [2] = "IBI_CALL_CS_SIGNAL_TYPE_IS54B_ALERT",
        [3] = "IBI_CALL_CS_SIGNAL_TYPE_RESERVED",
    },
    ["IBICallCsStatus"] = {
        [0] = "IBI_CALL_CS_MOC_CALL_SETUP",
        [1] = "IBI_CALL_CS_MOC_CALL_ALERTED",
        [2] = "IBI_CALL_CS_MOC_CALL_STARTED",
        [3] = "IBI_CALL_CS_MOC_CALL_ACTIVE",
        [4] = "IBI_CALL_CS_MTC_CALL_CONFIRMED",
        [5] = "IBI_CALL_CS_MTC_CALL_SETUP",
        [6] = "IBI_CALL_CS_MTC_BC_NEGOTIATED",
        [7] = "IBI_CALL_CS_MTC_CALL_STARTED",
        [8] = "IBI_CALL_CS_MTC_CALL_ACTIVE",
        [9] = "IBI_CALL_CS_MOC_AS_CALL_SETUP",
        [10] = "IBI_CALL_CS_MTC_AS_CALL_SETUP",
        [11] = "IBI_CALL_CS_MTC_CALL_REJECTED",
        [12] = "IBI_CALL_CS_CALL_IS_HELD",
        [13] = "IBI_CALL_CS_CALL_IS_RETRIEVED",
        [14] = "IBI_CALL_CS_MPARTY_IS_ACTIVE",
        [15] = "IBI_CALL_CS_MPARTY_IS_HELD",
        [16] = "IBI_CALL_CS_MPARTY_IS_RETRIEVED",
        [17] = "IBI_CALL_CS_MPARTY_IS_SPLITTED",
        [18] = "IBI_CALL_CS_IS_ECT",
        [19] = "IBI_CALL_CS_CALL_DISC_REQ",
        [20] = "IBI_CALL_CS_CALL_IS_DISCONNECTED",
        [21] = "IBI_CALL_CS_CALL_IS_CLEARED",
        [22] = "IBI_CALL_CS_CALL_MODIFY_INDICATED",
        [23] = "IBI_CALL_CS_CALL_MODIFY_STARTED",
        [24] = "IBI_CALL_CS_CALL_MODIFY_COMPLETED",
        [25] = "IBI_CALL_CS_CALL_MODIFY_REJECTED",
        [26] = "IBI_CALL_CS_CALL_IS_DEFLECTED",
        [27] = "IBI_CALL_CS_MPARTY_STARTED",
        [28] = "IBI_CALL_CS_MPARTY_REJECTED",
        [29] = "IBI_CALL_CS_MPARTY_RETRIEVE_STARTED",
        [30] = "IBI_CALL_CS_MPARTY_RETRIEVE_REJECTED",
        [31] = "IBI_CALL_CS_MPARTY_SPLIT_STARTED",
        [32] = "IBI_CALL_CS_MPARTY_SPLIT_REJECTED",
        [33] = "IBI_CALL_CS_MPARTY_HELD_STARTED",
        [34] = "IBI_CALL_CS_MPARTY_HELD_REJECTED",
        [35] = "IBI_CALL_CS_CALL_DEFLECTION_STARTED",
        [36] = "IBI_CALL_CS_CALL_DEFLECTION_REJECTED",
        [37] = "IBI_CALL_CS_CALL_HELD_STARTED",
        [38] = "IBI_CALL_CS_CALL_HELD_REJECTED",
        [39] = "IBI_CALL_CS_CALL_RETRIEVE_STARTED",
        [40] = "IBI_CALL_CS_CALL_RETRIEVE_REJECTED",
        [41] = "IBI_CALL_CS_ECT_STARTED",
        [42] = "IBI_CALL_CS_ECT_REJECTED",
        [43] = "IBI_CALL_CS_RADIO_LINK_FAILURE_DETECTED",
        [44] = "IBI_CALL_CS_REESTABLISHMENT_COMPLETED",
        [45] = "IBI_CALL_CS_CALL_PROCEEDING",
    },
    ["IBICallCsTtyDeviceMode"] = {
        [0] = "IBI_CALL_CS_TTY_DEVICE_MODE_OFF",
        [1] = "IBI_CALL_CS_TTY_DEVICE_MODE_AUTO",
        [2] = "IBI_CALL_CS_TTY_DEVICE_MODE_VCO",
        [3] = "IBI_CALL_CS_TTY_DEVICE_MODE_HCO",
    },
    ["IBICallCsType"] = {
        [0] = "IBI_CALL_CS_VOICE_CALL",
        [1] = "IBI_CALL_CS_DATA_CALL",
        [2] = "IBI_CALL_CS_EMERGENCY_CALL",
        [3] = "IBI_CALL_CS_VIDEO_CALL",
        [4] = "IBI_CALL_CS_FAX_CALL",
        [5] = "IBI_CALL_CS_MULTIMEDIA_CALL",
        [6] = "IBI_CALL_CS_INVALID_CALL_TYPE",
    },
    ["IBICallCsVoimsAuxiliaryState"] = {
        [0] = "IBI_CALL_CS_AUX_STATE_IDLE",
        [2] = "IBI_CALL_CS_AUX_STATE_HELD",
    },
    ["IBICallCsVoimsMMTelSessionStatus"] = {
        [0] = "IBI_CALL_CS_VOIMS_MMTEL_SESSION_STARTED",
        [1] = "IBI_CALL_CS_VOIMS_MMTEL_SESSION_FINISHED",
        [2] = "IBI_CALL_CS_VOIMS_MMTEL_SESSION_ATTEMPTED",
        [3] = "IBI_CALL_CS_VOIMS_MMTEL_SESSION_SETUP_FAILED",
        [4] = "IBI_CALL_CS_VOIMS_MMTEL_SESSION_DROPPED",
        [5] = "IBI_CALL_CS_VOIMS_MMTEL_SESSION_IMS_REGISTARTION_STARTED",
        [6] = "IBI_CALL_CS_VOIMS_MMTEL_SESSION_IMS_REGISTARTION_FINISHED",
        [7] = "IBI_CALL_CS_VOIMS_MMTEL_SESSION_IMS_REGISTARTION_FAILED",
    },
    ["IBICallCsVoimsMMTelSessionType"] = {
        [0] = "IBI_CALL_CS_VOIMS_MMTEL_SESSION_TYPE_VOICE_CALL",
        [1] = "IBI_CALL_CS_VOIMS_MMTEL_SESSION_TYPE_VIDEO_CALL",
        [2] = "IBI_CALL_CS_VOIMS_MMTEL_SESSION_TYPE_SMSOIP",
    },
    ["IBICallCsVoimsMptyAuxiliaryState"] = {
        [2] = "IBI_CALL_CS_MPTY_AUX_STATE_IN_MPTY",
        [0] = "IBI_CALL_CS_MPTY_AUX_STATE_IDLE",
    },
    ["IBICallCsVoimsRetryCause"] = {
        [0] = "IBI_CALL_CS_RETRY_CAUSE_EMERGENCY_CALL_SETUP",
        [1] = "IBI_CALL_CS_RETRY_CAUSE_NW_DETECTED_EMERGENCY_CALL",
        [2] = "IBI_CALL_CS_RETRY_CAUSE_IMS_SERVICE_NOT_AVAILABLE",
        [3] = "IBI_CALL_CS_RETRY_CAUSE_CELL_BARRED_MO_DATA",
    },
    ["IBICallCsVoimsSrvccCallState"] = {
        [0] = "IBI_CALL_CS_SRVCC_CALL_STATE_ACTIVE_U10",
        [1] = "IBI_CALL_CS_SRVCC_CALL_STATE_DELIVERED_U4",
        [2] = "IBI_CALL_CS_SRVCC_CALL_STATE_RECEIVED_U7",
        [3] = "IBI_CALL_CS_SRVCC_CALL_STATE_RECEIVED_CONFIRMED",
        [4] = "IBI_CALL_CS_SRVCC_CALL_STATE_MO_CALL_PROCEEDING_U3",
    },
    ["IBICallCsVoimsSrvccHoStatus"] = {
        [0] = "IBI_CALL_CS_SRVCC_HO_STARTED",
        [1] = "IBI_CALL_CS_SRVCC_HO_COMPLETE",
        [2] = "IBI_CALL_CS_SRVCC_HO_FAILED",
        [3] = "IBI_CALL_CS_SRVCC_HO_IMS_SYNCH_NEEDED",
        [4] = "IBI_CALL_CS_SRVCC_HO_LIKELY",
    },
    ["IBICallCsWaitingIndicator"] = {
        [1] = "IBI_CALL_CS_CALL_WAITING_NEW_CALL",
    },
    ["IBICallPsActivationStatus"] = {
        [0] = "IBI_CALL_PS_ACTIVATION_STATUS_ACCEPTED",
        [1] = "IBI_CALL_PS_ACTIVATION_STATUS_REJECTED",
        [2] = "IBI_CALL_PS_ACTIVATION_STATUS_5_TIME_T3380_EXPIRY",
        [3] = "IBI_CALL_PS_ACTIVATION_STATUS_USER_INTERRUPTION",
        [4] = "IBI_CALL_PS_ACTIVATION_STATUS_UNKNOWN",
    },
    ["IBICallPsAddressAndMaskIpType"] = {
        [1] = "IBI_CALL_PS_ADD_MASK_IP_TYPE_V6",
        [0] = "IBI_CALL_PS_ADD_MASK_IP_TYPE_V4",
    },
    ["IBICallPsApnSettingsBitmask"] = {
        [1] = "IBI_CALL_PS_ATTACH_APN_SETTING_HOME_1",
        [2] = "IBI_CALL_PS_ATTACH_APN_SETTING_ROAM_1",
        [3] = "???",
        [4] = "IBI_CALL_PS_ATTACH_APN_SETTING_HOME_2",
        [5] = "???",
        [6] = "???",
        [7] = "???",
        [8] = "IBI_CALL_PS_ATTACH_APN_SETTING_ROAM_2",
    },
    ["IBICallPsAuthenticationType"] = {
        [0] = "IBI_CALL_PS_AUTHENTICATION_TYPE_NONE",
        [1] = "IBI_CALL_PS_AUTHENTICATION_TYPE_PAP",
        [2] = "IBI_CALL_PS_AUTHENTICATION_TYPE_CHAP",
    },
    ["IBICallPsConnectionStateType"] = {
        [0] = "CONN_STATE_IDLE",
        [1] = "CONN_STATE_CONNECTED",
    },
    ["IBICallPsConnectionTriggerType"] = {
        [0] = "CONN_TRIGGER_SHORT_START",
        [1] = "CONN_TRIGGER_SHORT_END",
        [2] = "CONN_TRIGGER_LONG_START",
        [3] = "CONN_TRIGGER_LONG_END",
        [4] = "CONN_TRIGGER_MAX",
    },
    ["IBICallPsDelayClass"] = {
        [0] = "IBI_CALL_PS_DELAY_CLASS_SUBSCRIBED",
        [1] = "IBI_CALL_PS_DELAY_CLASS_1",
        [2] = "IBI_CALL_PS_DELAY_CLASS_2",
        [3] = "IBI_CALL_PS_DELAY_CLASS_3",
        [4] = "IBI_CALL_PS_DELAY_CLASS_4",
        [5] = "IBI_CALL_PS_DELAY_CLASS_RESERVED",
    },
    ["IBICallPsDeliveryOrder"] = {
        [0] = "IBI_CALL_PS_DELIVERY_ORDER_SUBSCRIBED",
        [1] = "IBI_CALL_PS_DELIVERY_ORDER_YES",
        [2] = "IBI_CALL_PS_DELIVERY_ORDER_NO",
        [3] = "IBI_CALL_PS_DELIVERY_ORDER_RESERVED",
    },
    ["IBICallPsErroneousSduDelivery"] = {
        [0] = "IBI_CALL_PS_ERRONEOUS_SDU_DELIVERY_SUBSCRIBED",
        [1] = "IBI_CALL_PS_ERRONEOUS_SDU_DELIVERY_NO_DETECTION",
        [2] = "IBI_CALL_PS_ERRONEOUS_SDU_DELIVERY_YES",
        [3] = "IBI_CALL_PS_ERRONEOUS_SDU_DELIVERY_NO",
        [4] = "IBI_CALL_PS_ERRONEOUS_SDU_DELIVERY_RESERVED",
    },
    ["IBICallPsEvsAudioBWType"] = {
        [0] = "IBI_EVS_NB",
        [1] = "IBI_EVS_WB",
        [2] = "IBI_EVS_SWB",
        [3] = "IBI_EVS_OTHER",
    },
    ["IBICallPsEvsBitRateType"] = {
        [0] = "IBI_EVS_5_9_Kbps",
        [1] = "IBI_EVS_7_2_Kbps",
        [2] = "IBI_EVS_8_0_Kbps",
        [3] = "IBI_EVS_9_6_Kbps",
        [4] = "IBI_EVS_13_2_Kbps",
        [5] = "IBI_EVS_16_4_Kbps",
        [6] = "IBI_EVS_24_4_Kbps",
        [7] = "IBI_EVS_32_0_Kbps",
        [8] = "IBI_EVS_48_0_Kbps",
        [9] = "IBI_EVS_64_0_Kbps",
        [10] = "IBI_EVS_96_0_Kbps",
        [11] = "IBI_EVS_128_0_Kbps",
    },
    ["IBICallPsLlcSapi"] = {
        [0] = "IBI_CALL_PS_LLC_SAPI_NOT_ASSIGNED",
        [1] = "???",
        [2] = "???",
        [3] = "IBI_CALL_PS_LLC_SAPI_SAPI_3",
        [4] = "???",
        [5] = "IBI_CALL_PS_LLC_SAPI_SAPI_5",
        [6] = "???",
        [7] = "???",
        [8] = "???",
        [9] = "IBI_CALL_PS_LLC_SAPI_SAPI_9",
        [10] = "???",
        [11] = "IBI_CALL_PS_LLC_SAPI_SAPI_11",
    },
    ["IBICallPsMBIMType"] = {
        [536870911] = "IBI_CALL_PS_MBIM_MAXENUMSIZE",
        [1] = "IBI_CALL_PS_MBIM_ICMP_ECHO_REQUEST",
    },
    ["IBICallPsMeanThroughput"] = {
        [0] = "IBI_CALL_PS_MEAN_THROUGHPUT_SUBSCRIBED",
        [1] = "IBI_CALL_PS_MEAN_THROUGHPUT_100",
        [2] = "IBI_CALL_PS_MEAN_THROUGHPUT_200",
        [3] = "IBI_CALL_PS_MEAN_THROUGHPUT_500",
        [4] = "IBI_CALL_PS_MEAN_THROUGHPUT_1K",
        [5] = "IBI_CALL_PS_MEAN_THROUGHPUT_2K",
        [6] = "IBI_CALL_PS_MEAN_THROUGHPUT_5K",
        [7] = "IBI_CALL_PS_MEAN_THROUGHPUT_10K",
        [8] = "IBI_CALL_PS_MEAN_THROUGHPUT_20K",
        [9] = "IBI_CALL_PS_MEAN_THROUGHPUT_50K",
        [10] = "IBI_CALL_PS_MEAN_THROUGHPUT_100K",
        [11] = "IBI_CALL_PS_MEAN_THROUGHPUT_200K",
        [12] = "IBI_CALL_PS_MEAN_THROUGHPUT_500K",
        [13] = "IBI_CALL_PS_MEAN_THROUGHPUT_1M",
        [14] = "IBI_CALL_PS_MEAN_THROUGHPUT_2M",
        [15] = "IBI_CALL_PS_MEAN_THROUGHPUT_5M",
        [16] = "IBI_CALL_PS_MEAN_THROUGHPUT_10M",
        [17] = "IBI_CALL_PS_MEAN_THROUGHPUT_20M",
        [18] = "IBI_CALL_PS_MEAN_THROUGHPUT_50M",
        [19] = "???",
        [20] = "???",
        [21] = "???",
        [22] = "???",
        [23] = "???",
        [24] = "???",
        [25] = "???",
        [26] = "???",
        [27] = "???",
        [28] = "???",
        [29] = "???",
        [30] = "IBI_CALL_PS_MEAN_THROUGHPUT_RESERVED",
        [31] = "IBI_CALL_PS_MEAN_THROUGHPUT_BEST_EFFORT",
    },
    ["IBICallPsNotificationIndicator"] = {
        [1] = "IBI_CALL_PS_NOTIFICATION_INDICATOR_SRVCC_HANDOVER_CANCELLED",
    },
    ["IBICallPsOrigin"] = {
        [0] = "IBI_CALL_PS_ORIGIN_NETWORK",
        [1] = "IBI_CALL_PS_ORIGIN_MOBILESTATION",
    },
    ["IBICallPsPDPReqType"] = {
        [1] = "IBI_CALL_PS_INITIAL",
        [2] = "IBI_CALL_PS_HANDOVER",
        [3] = "???",
        [4] = "IBI_CALL_PS_EMERGENCY",
    },
    ["IBICallPsPeakThroughput"] = {
        [0] = "IBI_CALL_PS_PEAK_THROUGHPUT_SUBSCRIBED",
        [1] = "IBI_CALL_PS_PEAK_THROUGHPUT_1K",
        [2] = "IBI_CALL_PS_PEAK_THROUGHPUT_2K",
        [3] = "IBI_CALL_PS_PEAK_THROUGHPUT_4K",
        [4] = "IBI_CALL_PS_PEAK_THROUGHPUT_8K",
        [5] = "IBI_CALL_PS_PEAK_THROUGHPUT_16K",
        [6] = "IBI_CALL_PS_PEAK_THROUGHPUT_32K",
        [7] = "IBI_CALL_PS_PEAK_THROUGHPUT_64K",
        [8] = "IBI_CALL_PS_PEAK_THROUGHPUT_128K",
        [9] = "IBI_CALL_PS_PEAK_THROUGHPUT_256K",
        [10] = "IBI_CALL_PS_PEAK_THROUGHPUT_RESERVED",
    },
    ["IBICallPsPrecedenceClass"] = {
        [0] = "IBI_CALL_PS_PRECEDENCE_CLASS_SUBSCRIBED",
        [1] = "IBI_CALL_PS_PRECEDENCE_CLASS_HIGH",
        [2] = "IBI_CALL_PS_PRECEDENCE_CLASS_NORMAL",
        [3] = "IBI_CALL_PS_PRECEDENCE_CLASS_LOW",
        [4] = "IBI_CALL_PS_PRECEDENCE_CLASS_RESERVED",
    },
    ["IBICallPsRadioPriority"] = {
        [1] = "IBI_CALL_PS_RADIO_PRIORITY_1",
        [2] = "IBI_CALL_PS_RADIO_PRIORITY_2",
        [3] = "IBI_CALL_PS_RADIO_PRIORITY_3",
        [4] = "IBI_CALL_PS_RADIO_PRIORITY_4",
    },
    ["IBICallPsReliabilityClass"] = {
        [0] = "IBI_CALL_PS_RELIABILITY_CLASS_SUBSCRIBED",
        [1] = "IBI_CALL_PS_RELIABILITY_CLASS_1",
        [2] = "IBI_CALL_PS_RELIABILITY_CLASS_2",
        [3] = "IBI_CALL_PS_RELIABILITY_CLASS_3",
        [4] = "IBI_CALL_PS_RELIABILITY_CLASS_4",
        [5] = "IBI_CALL_PS_RELIABILITY_CLASS_5",
        [6] = "IBI_CALL_PS_RELIABILITY_CLASS_6",
        [7] = "IBI_CALL_PS_RELIABILITY_CLASS_RESERVED",
    },
    ["IBICallPsResidualBitErrorRate"] = {
        [0] = "IBI_CALL_PS_RESIDUAL_BIT_ERROR_RATE_SUBSCRIBED",
        [1] = "IBI_CALL_PS_RESIDUAL_BIT_ERROR_RATE_5E2",
        [2] = "IBI_CALL_PS_RESIDUAL_BIT_ERROR_RATE_1E2",
        [3] = "IBI_CALL_PS_RESIDUAL_BIT_ERROR_RATE_5E3",
        [4] = "IBI_CALL_PS_RESIDUAL_BIT_ERROR_RATE_4E3",
        [5] = "IBI_CALL_PS_RESIDUAL_BIT_ERROR_RATE_1E3",
        [6] = "IBI_CALL_PS_RESIDUAL_BIT_ERROR_RATE_1E4",
        [7] = "IBI_CALL_PS_RESIDUAL_BIT_ERROR_RATE_1E5",
        [8] = "IBI_CALL_PS_RESIDUAL_BIT_ERROR_RATE_1E6",
        [9] = "IBI_CALL_PS_RESIDUAL_BIT_ERROR_RATE_6E8",
        [10] = "IBI_CALL_PS_RESIDUAL_BIT_ERROR_RATE_RESERVED",
    },
    ["IBICallPsSduErrorRatio"] = {
        [0] = "IBI_CALL_PS_SDU_ERROR_RATIO_SUBSCRIBED",
        [1] = "IBI_CALL_PS_SDU_ERROR_RATIO_1E2",
        [2] = "IBI_CALL_PS_SDU_ERROR_RATIO_7E3",
        [3] = "IBI_CALL_PS_SDU_ERROR_RATIO_1E3",
        [4] = "IBI_CALL_PS_SDU_ERROR_RATIO_1E4",
        [5] = "IBI_CALL_PS_SDU_ERROR_RATIO_1E5",
        [6] = "IBI_CALL_PS_SDU_ERROR_RATIO_1E6",
        [7] = "IBI_CALL_PS_SDU_ERROR_RATIO_1E1",
        [8] = "IBI_CALL_PS_SDU_ERROR_RATIO_RESERVED",
    },
    ["IBICallPsSignalingIndicator"] = {
        [0] = "IBI_CALL_PS_SIGNALING_INDICATOR_SUBSCRIBED",
        [1] = "IBI_CALL_PS_SIGNALING_INDICATOR_1",
        [2] = "IBI_CALL_PS_SIGNALING_INDICATOR_RESERVED",
    },
    ["IBICallPsSourceStatisticsDesc"] = {
        [0] = "IBI_CALL_PS_SOURCE_STATISTICS_DESC_SUBSCRIBED",
        [1] = "IBI_CALL_PS_SOURCE_STATISTICS_DESC_1",
        [2] = "IBI_CALL_PS_SOURCE_STATISTICS_DESC_RESERVED",
    },
    ["IBICallPsStopDataCallReason"] = {
        [0] = "IBI_CALL_PS_STOP_DATA_CALL_REASON_IPV6_ADDR_FORMATION_FAILURE",
        [1] = "IBI_CALL_PS_STOP_DATA_CALL_REASON_IPV6_ADDR_REFRESH_FAILURE",
        [255] = "IBI_CALL_PS_STOP_DATA_CALL_REASON_INVALID",
    },
    ["IBICallPsSuspendCause"] = {
        [1] = "IBI_CALL_PS_SUSPEND_CAUSE_NO_SERVICE",
        [2] = "IBI_CALL_PS_SUSPEND_CAUSE_RAT_CHANGE",
        [3] = "IBI_CALL_PS_SUSPEND_CAUSE_GPRS_HOLD_SMS",
        [4] = "IBI_CALL_PS_SUSPEND_CAUSE_GPRS_HOLD_CALL",
        [5] = "IBI_CALL_PS_SUSPEND_CAUSE_GPRS_HOLD_LU",
        [6] = "IBI_CALL_PS_SUSPEND_CAUSE_GPRS_HOLD_OTHER",
        [7] = "IBI_CALL_PS_SUSPEND_CAUSE_FLOW_CONTROL",
        [8] = "IBI_CALL_PS_SUSPEND_CAUSE_GPRS_SUSPEND",
        [9] = "IBI_CALL_PS_SUSPEND_CAUSE_ROUTING_AREA_UPDATE",
        [10] = "IBI_CALL_PS_SUSPEND_CAUSE_NO_SERVICE_DUAL_SIM_CONFLICT",
    },
    ["IBICallPsTftDirection"] = {
        [0] = "IBI_CALL_PS_TFT_DIRECTION_PRE_REL7",
        [1] = "IBI_CALL_PS_TFT_DIRECTION_UPLINK",
        [2] = "IBI_CALL_PS_TFT_DIRECTION_DOWNLINK",
        [3] = "IBI_CALL_PS_TFT_DIRECTION_BIDIRECTIONAL",
    },
    ["IBICallPsTrafficClass"] = {
        [0] = "IBI_CALL_PS_TRAFFIC_CLASS_SUBSCRIBED",
        [1] = "IBI_CALL_PS_TRAFFIC_CLASS_CONVERSATIONAL",
        [2] = "IBI_CALL_PS_TRAFFIC_CLASS_STREAMING",
        [3] = "IBI_CALL_PS_TRAFFIC_CLASS_INTERACTIVE",
        [4] = "IBI_CALL_PS_TRAFFIC_CLASS_BACKGROUND",
        [5] = "IBI_CALL_PS_TRAFFIC_CLASS_RESERVED",
    },
    ["IBICallPsTrafficPriority"] = {
        [0] = "IBI_CALL_PS_TRAFFIC_PRIORITY_SUBSCRIBED",
        [1] = "IBI_CALL_PS_TRAFFIC_PRIORITY_1",
        [2] = "IBI_CALL_PS_TRAFFIC_PRIORITY_2",
        [3] = "IBI_CALL_PS_TRAFFIC_PRIORITY_3",
        [4] = "IBI_CALL_PS_TRAFFIC_PRIORITY_RESERVED",
    },
    ["IBICallPsTransmitStateInfoType"] = {
        [0] = "TRANSMIT_STATE_INFO_DISABLED",
        [1] = "TRANSMIT_STATE_INFO_ENABLED",
        [2] = "TRANSMIT_STATE_INFO_MAX",
    },
    ["IBICallPsVoLTECodecType"] = {
        [0] = "IBI_AMR_NB",
        [1] = "IBI_AMR_WB",
        [2] = "IBI_EVS_PRIMARY",
        [3] = "IBI_EVS_IO",
        [4] = "IBI_EVS_CA",
        [5] = "IBI_OTHER",
    },
    ["IBICallType"] = {
        [0] = "IBI_SIP_CALL_TYPE_NA",
        [1] = "IBI_SIP_CALL_TYPE_NORMAL",
        [2] = "IBI_SIP_CALL_TYPE_HOLD",
        [3] = "IBI_SIP_CALL_TYPE_UNHOLD",
        [4] = "IBI_SIP_CALL_TYPE_WAITING",
        [5] = "IBI_SIP_CALL_TYPE_CONFERENCE",
        [6] = "IBI_SIP_CALL_TYPE_FORWARD",
        [7] = "IBI_SIP_CALL_TYPE_TRANSFER",
    },
    ["IBICbsCause"] = {
        [0] = "IBI_CBS_CAUSE_NO_CAUSE",
        [1] = "IBI_CBS_CAUSE_CONFIG_UNKNOWN_WARNING",
        [2] = "IBI_CBS_CAUSE_CONFIG_NOT_ENABLED",
        [3] = "IBI_CBS_CAUSE_CONFIG_NOT_CONFIGURED",
        [4] = "IBI_CBS_CAUSE_CONFIG_INVALID_CONFIGURATION",
        [5] = "IBI_CBS_CAUSE_CONFIG_NOT_STARTED",
        [6] = "IBI_CBS_CAUSE_CONFIG_SECONDARY_FAIL",
        [7] = "IBI_CBS_CAUSE_CONFIG_PRIM_SUCCESS_SEC_FAIL",
        [8] = "IBI_CBS_CAUSE_CONFIG_TEST_MODE",
        [9] = "IBI_CBS_CAUSE_CONFIG_SKIP",
        [10] = "IBI_CBS_CAUSE_CONFIG_ACTIVE",
        [11] = "IBI_CBS_CAUSE_CONFIG_UNSPECIFIED",
        [12] = "IBI_CBS_CAUSE_CBS_START_FAILED",
        [13] = "IBI_CBS_CAUSE_CBS_INTERNAL_FAILURE",
    },
    ["IBICbsEtwsWarningType"] = {
        [0] = "IBI_CBS_ETWS_WARNING_EARTHQUAKE",
        [1] = "IBI_CBS_ETWS_WARNING_TSUNAMI",
        [2] = "IBI_CBS_ETWS_WARNING_EARTHQUAKE_TSUNAMI",
        [3] = "IBI_CBS_ETWS_WARNING_TEST",
        [4] = "IBI_CBS_ETWS_WARNING_OTHER",
    },
    ["IBICbsType"] = {
        [0] = "IBI_CBS_TYPE_CBS",
        [1] = "IBI_CBS_TYPE_CMAS",
        [2] = "IBI_CBS_TYPE_ETWS_SECONDARY",
        [3] = "IBI_CBS_TYPE_ETWS_PRIMARY",
    },
    ["IBICdmaLanguage"] = {
        [0] = "IBI_CDMA_LANGUAGE_UNKNOWN",
        [1] = "IBI_CDMA_LANGUAGE_ENGLISH",
        [2] = "IBI_CDMA_LANGUAGE_FRENCH",
        [3] = "IBI_CDMA_LANGUAGE_SPANISH",
        [4] = "IBI_CDMA_LANGUAGE_JAPANESE",
        [5] = "IBI_CDMA_LANGUAGE_KOREAN",
        [6] = "IBI_CDMA_LANGUAGE_CHINESE",
        [7] = "IBI_CDMA_LANGUAGE_HEBREW",
        [8] = "IBI_CDMA_LANGUAGE_PORTUGUESE",
        [9] = "IBI_CDMA_LANGUAGE_HINDI",
        [10] = "IBI_CDMA_LANGUAGE_TURKISH",
        [11] = "IBI_CDMA_LANGUAGE_HUNGARIAN",
        [12] = "IBI_CDMA_LANGUAGE_POLISH",
        [13] = "IBI_CDMA_LANGUAGE_CZECH",
        [14] = "IBI_CDMA_LANGUAGE_ARABIC",
        [15] = "IBI_CDMA_LANGUAGE_RUSSIAN",
        [16] = "IBI_CDMA_LANGUAGE_ICELANDIC",
        [17] = "IBI_CDMA_LANGUAGE_GERMAN",
        [18] = "IBI_CDMA_LANGUAGE_ITALIAN",
        [19] = "IBI_CDMA_LANGUAGE_DUTCH",
        [20] = "IBI_CDMA_LANGUAGE_SWEDISH",
        [21] = "IBI_CDMA_LANGUAGE_DANISH",
        [22] = "???",
        [23] = "IBI_CDMA_LANGUAGE_FINNISH",
        [24] = "IBI_CDMA_LANGUAGE_NORWEGIAN",
        [25] = "IBI_CDMA_LANGUAGE_GREEK",
        [26] = "IBI_CDMA_LANGUAGE_BENGALI",
        [27] = "IBI_CDMA_LANGUAGE_GUJARATI",
        [28] = "IBI_CDMA_LANGUAGE_KANNADA",
        [29] = "IBI_CDMA_LANGUAGE_MALAYALAM",
        [30] = "IBI_CDMA_LANGUAGE_ORIYA",
        [31] = "IBI_CDMA_LANGUAGE_PUNJABI",
        [32] = "IBI_CDMA_LANGUAGE_TAMIL",
        [33] = "IBI_CDMA_LANGUAGE_TELUGU",
        [34] = "IBI_CDMA_LANGUAGE_URDU",
        [35] = "IBI_CDMA_LANGUAGE_BAHASA",
        [36] = "IBI_CDMA_LANGUAGE_THAI",
        [37] = "IBI_CDMA_LANGUAGE_TAGALOG",
        [38] = "IBI_CDMA_LANGUAGE_SWAHILI",
        [39] = "IBI_CDMA_LANGUAGE_AFRIKAANS",
        [40] = "IBI_CDMA_LANGUAGE_HAUSA",
        [41] = "IBI_CDMA_LANGUAGE_VIETNAMESE",
    },
    ["IBICdmaPsRatType"] = {
        [0] = "IBI_CDMA_PS_RAT_HRPD",
        [1] = "IBI_CDMA_PS_RAT_EHRPD",
    },
    ["IBICdmaSmsErrorClass"] = {
        [0] = "IBI_CDMA_ERROR_CLASS_TEMPORARY",
        [1] = "IBI_CDMA_ERROR_CLASS_PERMANENT",
    },
    ["IBICellErrorT"] = {
        [0] = "IBI_CELL_ERR_NONE",
        [1] = "IBI_CELL_INVALID_RAT",
        [2] = "IBI_CELL_INVALID_INFO",
        [3] = "IBI_CELL_INVALID_NETWORK",
    },
    ["IBICellResultT"] = {
        [0] = "IBI_CELL_RESULT_SUCCESS",
        [1] = "IBI_CELL_RESULT_FAILURE",
    },
    ["IBIClsModemState"] = {
        [0] = "IBI_CLS_CELL_DCH",
        [1] = "IBI_CLS_CELL_FACH",
        [2] = "IBI_CLS_INVALID_STATE",
    },
    ["IBIClsNetworkType"] = {
        [0] = "IBI_CLS_GERAN_NETWORK",
        [1] = "IBI_CLS_UTRAN_NETWORK",
        [2] = "IBI_CLS_EUTRAN_NETWORK",
        [3] = "IBI_CLS_INVALID_NETWORK",
    },
    ["IBICnDomain"] = {
        [1] = "IBI_CN_CS_DOMAIN",
        [2] = "IBI_CN_PS_DOMAIN",
        [3] = "IBI_CN_ALL_DOMAIN",
    },
    ["IBICpsCellularPowerReportState"] = {
        [0] = "ICE_CPR_STATE_AIRPLANE_OR_IDLE_MODE",
        [1] = "ICE_CPR_STATE_VOICE_CALL",
        [2] = "ICE_CPR_STATE_GERA_UTRA_DATA",
        [3] = "ICE_CPR_STATE_EUTRA_2CA_DATA",
        [4] = "ICE_CPR_STATE_EUTRA_4CA_DATA",
        [5] = "ICE_CPR_STATE_COUNT",
    },
    ["IBICpsHealthActivityLocationType"] = {
        [0] = "IBI_HEALTH_ACTIVITY_LOCATION_TYPE_UNKNOWN",
        [1] = "IBI_HEALTH_ACTIVITY_LOCATION_TYPE_INDOOR",
        [2] = "IBI_HEALTH_ACTIVITY_LOCATION_TYPE_OUTDOOR",
        [3] = "IBI_HEALTH_ACTIVITY_LOCATION_TYPE_MAX",
    },
    ["IBICpsHealthActivityStatus"] = {
        [0] = "IBI_HEALTH_ACTIVITY_STATUS_STOP",
        [1] = "IBI_HEALTH_ACTIVITY_STATUS_START",
        [2] = "IBI_HEALTH_ACTIVITY_STATUS_PAUSE",
        [3] = "IBI_HEALTH_ACTIVITY_STATUS_MAX",
    },
    ["IBICpsHealthActivitySwimLocationType"] = {
        [0] = "IBI_HEALTH_ACTIVITY_SWIM_LOCATION_TYPE_UNKNOWN",
        [1] = "IBI_HEALTH_ACTIVITY_SWIM_LOCATION_TYPE_POOL",
        [2] = "IBI_HEALTH_ACTIVITY_SWIM_LOCATION_TYPE_OPEN_WATER",
        [3] = "IBI_HEALTH_ACTIVITY_SWIM_LOCATION_TYPE_MAX",
    },
    ["IBICpsHealthActivityType"] = {
        [0] = "IBI_HEALTH_ACTIVITY_TYPE_NONE",
        [1] = "IBI_HEALTH_ACTIVITY_TYPE_SWIM",
        [2] = "IBI_HEALTH_ACTIVITY_TYPE_WALK",
        [3] = "IBI_HEALTH_ACTIVITY_TYPE_ELLIPTICAL",
        [4] = "IBI_HEALTH_ACTIVITY_TYPE_CYCLE",
        [5] = "IBI_HEALTH_ACTIVITY_TYPE_STAIR_STEPPER",
        [6] = "IBI_HEALTH_ACTIVITY_TYPE_RUN",
        [7] = "IBI_HEALTH_ACTIVITY_TYPE_ROWER",
        [8] = "IBI_HEALTH_ACTIVITY_TYPE_HIGH_INTENSITY_INTERVAL_TRAINING",
        [9] = "IBI_HEALTH_ACTIVITY_TYPE_MAX",
    },
    ["IBICtsNetworkType"] = {
        [0] = "IBI_CTS_NETWORK_TYPE_EUTRAN",
        [1] = "IBI_CTS_NETWORK_TYPE_CDMA",
        [2] = "IBI_CTS_NETWORK_TYPE_INVALID",
    },
    ["IBIEmbmsGetSAIType"] = {
        [1] = "IBI_EMBMS_SAI_TYPE_USER_DEFINED",
        [0] = "IBI_EMBMS_SAI_TYPE_NETWORK_PROVIDED",
    },
    ["IBIEmbmsMBSFNAreaAvailability"] = {
        [0] = "IBI_EMBMS_MBSFN_AREA_LEAVING",
        [1] = "IBI_EMBMS_MBSFN_AREA_ENTERING",
        [2] = "IBI_EMBMS_MBSFN_AREA_READ_FAILED",
    },
    ["IBIEmbmsRejectCause"] = {
        [0] = "IBI_EMBMS_REJECT_CAUSE_NO_ERROR",
        [1] = "IBI_EMBMS_REJECT_CAUSE_EMBMS_INACTIVE",
        [2] = "IBI_EMBMS_REJECT_CAUSE_MAX_SUPPORTED_FREQ_EXCEEDED",
        [3] = "IBI_EMBMS_REJECT_CAUSE_FREQ_NOT_SUPPORTED",
        [4] = "IBI_EMBMS_REJECT_CAUSE_NOT_SPECIFIED",
    },
    ["IBIEmbmsServiceLossCause"] = {
        [0] = "IBI_EMBMS_SERVICE_LOSS_DUAL_SIM_BAND_CONFLICT",
        [1] = "IBI_EMBMS_SERVICE_LOSS_EMBMS_BAND_CONFLICT",
        [2] = "IBI_EMBMS_SERVICE_LOSS_NO_CELL_FOUND",
        [3] = "IBI_EMBMS_SERVICE_LOSS_OF_COVERAGE",
        [4] = "IBI_EMBMS_SERVICE_LOSS_LAST_TMGI_DEACTIVATED",
        [5] = "IBI_EMBMS_SERVICE_LOSS_UNSPECIFIED",
    },
    ["IBIEmbmsServiceSupport"] = {
        [1] = "IBI_EMBMS_SERVICE_ENABLE",
        [0] = "IBI_EMBMS_SERVICE_DISABLE",
    },
    ["IBIEmbmsServiceType"] = {
        [1] = "IBI_EMBMS_SERVICE_TYPE_CONFIGURED_SERVICES",
        [0] = "IBI_EMBMS_SERVICE_TYPE_AVAILABLE_SERVICES",
    },
    ["IBIImsMEAudioChannelModes"] = {
        [2] = "IBI_IMS_ME_AUDIOCHANNEL_MODE_STEREO",
        [1] = "IBI_IMS_ME_AUDIOCHANNEL_MODE_MONO",
    },
    ["IBIImsMEAudioCodecEVSType"] = {
        [1] = "IBI_IMS_ME_AUDIO_CODEC_EVS_PRIMARY",
        [2] = "IBI_IMS_ME_AUDIO_CODEC_EVS_AMRWB_IO",
    },
    ["IBIImsMEAudioCodecTypes"] = {
        [1] = "IBI_IMS_ME_AUDIO_CODEC_TYPE_G711U",
        [2] = "IBI_IMS_ME_AUDIO_CODEC_TYPE_G711A",
        [3] = "IBI_IMS_ME_AUDIO_CODEC_TYPE_AMRNB",
        [4] = "IBI_IMS_ME_AUDIO_CODEC_TYPE_AMRWB",
        [5] = "IBI_IMS_ME_AUDIO_CODEC_TYPE_TELEPHONY_EVENT",
        [6] = "IBI_IMS_ME_AUDIO_CODEC_TYPE_EVS",
    },
    ["IBIImsMEAudioEVSBandWidthType"] = {
        [1] = "IBI_IMS_ME_AUDIO_BAND_NB",
        [2] = "IBI_IMS_ME_AUDIO_BAND_WB",
        [3] = "???",
        [4] = "IBI_IMS_ME_AUDIO_BAND_SWB",
        [5] = "???",
        [6] = "???",
        [7] = "???",
        [8] = "IBI_IMS_ME_AUDIO_BAND_FB",
    },
    ["IBIImsMEDTMFCodes"] = {
        [0] = "IBI_IMS_ME_DTMF_DIGIT_CODE_0",
        [1] = "IBI_IMS_ME_DTMF_DIGIT_CODE_1",
        [2] = "IBI_IMS_ME_DTMF_DIGIT_CODE_2",
        [3] = "IBI_IMS_ME_DTMF_DIGIT_CODE_3",
        [4] = "IBI_IMS_ME_DTMF_DIGIT_CODE_4",
        [5] = "IBI_IMS_ME_DTMF_DIGIT_CODE_5",
        [6] = "IBI_IMS_ME_DTMF_DIGIT_CODE_6",
        [7] = "IBI_IMS_ME_DTMF_DIGIT_CODE_7",
        [8] = "IBI_IMS_ME_DTMF_DIGIT_CODE_8",
        [9] = "IBI_IMS_ME_DTMF_DIGIT_CODE_9",
        [10] = "IBI_IMS_ME_DTMF_DIGIT_CODE_ASTERIX",
        [11] = "IBI_IMS_ME_DTMF_DIGIT_CODE_HASH",
        [12] = "IBI_IMS_ME_DTMF_DIGIT_CODE_A",
        [13] = "IBI_IMS_ME_DTMF_DIGIT_CODE_B",
        [14] = "IBI_IMS_ME_DTMF_DIGIT_CODE_C",
        [15] = "IBI_IMS_ME_DTMF_DIGIT_CODE_D",
        [16] = "IBI_IMS_ME_DTMF_DIGIT_CODE_FLASH",
    },
    ["IBIImsMEMediaDirection"] = {
        [1] = "IBI_IMS_ME_MEDIA_DIRECTION_TX",
        [2] = "IBI_IMS_ME_MEDIA_DIRECTION_RX",
        [3] = "IBI_IMS_ME_MEDIA_DIRECTION_TRX",
    },
    ["IBIImsMEMediaType"] = {
        [1] = "IBI_IMS_ME_MEDIA_TYPE_AUDIO",
        [2] = "IBI_IMS_ME_MEDIA_TYPE_VIDEO",
        [3] = "IBI_IMS_ME_MEDIA_TYPE_RTT",
    },
    ["IBIImsMERTTCodecTypes"] = {
        [1] = "IBI_IMS_ME_RTT_CODEC_TYPE_T140",
    },
    ["IBIImsMEResult"] = {
        [0] = "IBI_IMS_ME_NO_ERROR",
        [1] = "IBI_IMS_ME_ALREADY_EXISTS",
        [2] = "IBI_IMS_ME_INVALID_SESSION_ID",
        [3] = "IBI_IMS_ME_INVALID_PARAMETERS",
        [4] = "IBI_IMS_ME_NETWORK_ERROR",
        [5] = "IBI_IMS_ME_ILLEGAL_STATE",
        [6] = "IBI_IMS_ME_MALLOC_FAILED",
        [7] = "IBI_IMS_ME_ERROR_UNKNOWN",
    },
    ["IBIImsMERtcpSdesItemType"] = {
        [0] = "IBI_IMS_ME_RTCP_SDES_END",
        [1] = "IBI_IMS_ME_RTCP_SDES_CNAME",
        [2] = "IBI_IMS_ME_RTCP_SDES_NAME",
        [3] = "IBI_IMS_ME_RTCP_SDES_EMAIL",
        [4] = "IBI_IMS_ME_RTCP_SDES_PHONE",
        [5] = "IBI_IMS_ME_RTCP_SDES_LOC",
        [6] = "IBI_IMS_ME_RTCP_SDES_TOOL",
        [7] = "IBI_IMS_ME_RTCP_SDES_NOTE",
        [8] = "IBI_IMS_ME_RTCP_SDES_PRIV",
    },
    ["IBIImsMERtpProfile"] = {
        [2] = "IBI_IMS_ME_RTP_PROFILE_AVPF",
        [1] = "IBI_IMS_ME_RTP_PROFILE_AVP",
    },
    ["IBIImsMERttSessionTtyMode"] = {
        [0] = "IBI_IMS_ME_RTT_SESSION_TTY_OFF",
        [1] = "IBI_IMS_ME_RTT_SESSION_TTY_FULL",
        [2] = "IBI_IMS_ME_RTT_SESSION_TTY_HCO",
        [3] = "IBI_IMS_ME_RTT_SESSION_TTY_VCO",
    },
    ["IBIImsMeRtcpSourceType"] = {
        [2] = "IBI_IMS_ME_RTCP_SOURCE_REMOTE",
        [1] = "IBI_IMS_ME_RTCP_SOURCE_LOCAL",
    },
    ["IBIImsTestReqType"] = {
        [0] = "IBI_IMS_ENABLE_TEST_MODE_REQ",
        [1] = "IBI_IMS_AT_COMMAND_RESPONSE",
    },
    ["IBILpAdditionalInfo"] = {
        [0] = "IBI_LP_ONLY_RETURN_INFO_REQUESTED",
        [1] = "IBI_LP_MAY_RETURN_ADDITIONAL_INFO",
        [2] = "IBI_LP_ADDITIONAL_INFO_INVALID",
    },
    ["IBILpDgpsStatus"] = {
        [0] = "IBI_LP_UDRE_SCALE_1_0",
        [1] = "IBI_LP_UDRE_SCALE_0_75",
        [2] = "IBI_LP_UDRE_SCALE_0_5",
        [3] = "IBI_LP_UDRE_SCALE_0_3",
        [4] = "IBI_LP_UDRE_SCALE_0_2",
        [5] = "IBI_LP_UDRE_SCALE_0_1",
        [6] = "IBI_LP_UDRE_SCALE_NO_DATA",
        [7] = "IBI_LP_UDRE_SCALE_INVALID_DATA",
    },
    ["IBILpDiscardedPosMsgType"] = {
        [0] = "IBI_LP_DISCARDED_POS_MSG_TYPE_CAPABILITY_REQ",
        [1] = "IBI_LP_DISCARDED_POS_MSG_TYPE_PROVIDE_ASSISTANCE_DATA",
        [2] = "IBI_LP_DISCARDED_POS_MSG_TYPE_REQUEST_LOCATION_INFO",
        [3] = "IBI_LP_DISCARDED_POS_MSG_TYPE_ERROR",
        [4] = "IBI_LP_DISCARDED_POS_MSG_TYPE_ABORT",
        [5] = "IBI_LP_DISCARDED_POS_MSG_TYPE_TEST_RESET",
        [6] = "IBI_LP_DISCARDED_POS_MSG_TYPE_TEST_UPDATE_LOCATION",
    },
    ["IBILpEnvironment"] = {
        [0] = "IBI_LP_BAD_AREA",
        [1] = "IBI_LP_NOT_BAD_AREA",
        [2] = "IBI_LP_MIXED_AREA",
        [3] = "IBI_LP_ENV_INVALID",
    },
    ["IBILpFixType"] = {
        [1] = "IBI_LP_FIX_TYPE_3D",
        [0] = "IBI_LP_FIX_TYPE_2D",
    },
    ["IBILpGanssId"] = {
        [0] = "IBI_LP_GANSS_ID_SBAS",
        [1] = "IBI_LP_GANSS_ID_MODERNISED_GPS",
        [2] = "IBI_LP_GANSS_ID_QZSS",
        [3] = "IBI_LP_GANSS_ID_GLONASS",
        [4] = "IBI_LP_GANSS_ID_GALILEO",
        [5] = "IBI_LP_GANSS_ID_INVALID",
    },
    ["IBILpGnssToId"] = {
        [0] = "IBI_LP_GNSS_TO_ID_GPS",
        [1] = "???",
        [2] = "IBI_LP_GNSS_TO_ID_GALILEO",
        [3] = "IBI_LP_GNSS_TO_ID_QZSS",
        [4] = "IBI_LP_GNSS_TO_ID_GLONASS",
        [5] = "IBI_LP_GNSS_TO_ID_INVALID",
    },
    ["IBILpIs801LocationIndStatus"] = {
        [0] = "IBI_LP_IS801_LOCATION_IND_SUCCESS",
        [1] = "IBI_LP_IS801_LOCATION_IND_ERROR",
    },
    ["IBILpLocationRequestStatus"] = {
        [0] = "IBI_LP_LOCATION_REQUEST_STATUS_START",
        [1] = "IBI_LP_LOCATION_REQUEST_STATUS_END",
    },
    ["IBILpLocationServerErrorCause"] = {
        [0] = "IBI_LP_LOCATION_SERVER_ERROR_CAUSE_NOT_PRESENT",
        [1] = "IBI_LP_LOCATION_SERVER_ERROR_CAUSE_UNDEFINED",
        [2] = "IBI_LP_LOCATION_SERVER_ERROR_CAUSE_UNDELIVERED_ASSIST_DATA_NOT_SUPPORTED",
        [3] = "IBI_LP_LOCATION_SERVER_ERROR_CAUSE_ASSIST_DATA_NOT_CURRENTLY_AVAILABLE",
        [4] = "IBI_LP_LOCATION_SERVER_ERROR_CAUSE_ASSIST_DATA_PARTLY_NOT_SUPPORTED_PARTLY_NOT_AVAILABLE",
    },
    ["IBILpMethodType"] = {
        [0] = "IBI_LP_METHOD_MSASSISTED",
        [1] = "IBI_LP_METHOD_MSBASED",
        [2] = "IBI_LP_METHOD_STANDALONE",
    },
    ["IBILpMultipathIndicator"] = {
        [0] = "IBI_LP_MULTI_PATH_NOT_MEASURED",
        [1] = "IBI_LP_MULTI_PATH_LOW",
        [2] = "IBI_LP_MULTI_PATH_MEDIUM",
        [3] = "IBI_LP_MULTI_PATH_HIGH",
        [4] = "IBI_LP_MULTI_PATH_INVALID",
    },
    ["IBILpPosProtocol"] = {
        [0] = "IBI_LP_RRLP",
        [1] = "IBI_LP_RRC",
        [2] = "IBI_LP_LPP",
        [3] = "IBI_LP_IS801",
    },
    ["IBILpSessionProtocol"] = {
        [0] = "IBI_LP_SESSION_CPLANE",
        [1] = "IBI_LP_SESSION_UPLANE",
        [2] = "IBI_LP_SESSION_USER",
        [3] = "IBI_LP_SESSION_MODEM",
    },
    ["IBILpUtranSfnGpsUncertainty"] = {
        [0] = "IBI_LP_UTRAN_SFN_GPS_UNCERTAINTY_LESS_THAN_10MS",
        [1] = "IBI_LP_UTRAN_SFN_GPS_UNCERTAINTY_MORE_THAN_10MS",
        [2] = "IBI_LP_UTRAN_SFN_GPS_UNCERTAINTY_NOT_PRESENT",
    },
    ["IBIMSimConfigMode"] = {
        [0] = "IBI_MSIM_CONFIG_SSIM_MODE",
        [1] = "IBI_MSIM_CONFIG_MSIM_MODE",
    },
    ["IBIMSimRemapStatus"] = {
        [0] = "IBI_MSIM_REMAP_NEEDED",
        [1] = "IBI_MSIM_REMAP_START",
        [2] = "IBI_MSIM_REMAP_COMPLETE",
    },
    ["IBIMessageMode"] = {
        [1] = "IBI_MESSAGE_MODE_3GPP2",
        [0] = "IBI_MESSAGE_MODE_3GPP",
    },
    ["IBIMode"] = {
        [0] = "IBI_MODE_MINIMAL",
        [1] = "IBI_MODE_NORMAL",
        [2] = "IBI_MODE_AIRPLANE",
        [3] = "IBI_MODE_CALIBRATION",
        [4] = "IBI_MODE_PRODUCTION_TEST",
        [5] = "IBI_MODE_ALARM",
        [6] = "IBI_MODE_CHARGE_ONLY",
        [7] = "IBI_MODE_FORCED_SLEEP",
    },
    ["IBIMsimConfigStatus"] = {
        [0] = "IBI_MSIM_CONFIG_STATUS_SUCCESS",
        [1] = "IBI_MSIM_CONFIG_STATUS_FAILURE_UNKNOWN",
        [2] = "IBI_MSIM_CONFIG_INVALID_CONFIG",
        [3] = "IBI_MSIM_CONFIG_STATUS_FAILURE_ACTIVE_VOICE",
    },
    ["IBINetApBatterySaverModeType"] = {
        [0] = "IBI_NET_AP_BATTERY_SAVER_OFF",
        [1] = "IBI_NET_AP_BATTERY_SAVER_ON",
        [2] = "IBI_NET_AP_BATTERY_SAVER_INVALID",
    },
    ["IBINetApScreenLockStatusType"] = {
        [0] = "IBI_NET_AP_SCREEN_UNLOCKED",
        [1] = "IBI_NET_AP_SCREEN_LOCKED",
        [2] = "IBI_NET_AP_SCREEN_LOCK_INVALID",
    },
    ["IBINetApScreenStatusType"] = {
        [0] = "IBI_NET_AP_SCREEN_STATUS_ON",
        [1] = "IBI_NET_AP_SCREEN_STATUS_DIM",
        [2] = "IBI_NET_AP_SCREEN_STATUS_OFF",
        [3] = "IBI_NET_AP_SCREEN_STATUS_INVALID",
    },
    ["IBINetApSleepStatusType"] = {
        [0] = "IBI_NET_AP_STATUS_SLEEP",
        [1] = "IBI_NET_AP_STATUS_AWAKE",
        [2] = "IBI_NET_AP_STATUS_INVALID",
    },
    ["IBINetApTetheringStatusType"] = {
        [0] = "IBI_NET_AP_TETHERING_ON",
        [1] = "IBI_NET_AP_TETHERING_OFF",
        [2] = "IBI_NET_AP_TETHERING_INVALID",
    },
    ["IBINetAreaType"] = {
        [1] = "IBI_NET_AREA_TYPE_TAI",
        [0] = "IBI_NET_AREA_TYPE_RAI",
    },
    ["IBINetBand"] = {
        [0] = "IBI_NET_BAND_GSM900",
        [1] = "IBI_NET_BAND_GSM900_P",
        [2] = "IBI_NET_BAND_GSM900_E",
        [3] = "IBI_NET_BAND_GSM900_R",
        [4] = "IBI_NET_BAND_GSM1800",
        [5] = "IBI_NET_BAND_GSM1900",
        [6] = "IBI_NET_BAND_GSM850",
        [7] = "IBI_NET_BAND_GSM450",
        [8] = "IBI_NET_BAND_GSM480",
        [9] = "IBI_NET_BAND_GSM750",
        [10] = "IBI_NET_BAND_GSM_T_GSM380",
        [11] = "IBI_NET_BAND_GSM_T_GSM410",
        [12] = "IBI_NET_BAND_GSM_T_GSM900",
        [13] = "IBI_NET_BAND_GSM710",
        [14] = "IBI_NET_BAND_GSM_T_GSM810",
        [15] = "IBI_NET_BAND_MULTI",
        [16] = "IBI_NET_BAND_UMTS_FDD",
        [17] = "IBI_NET_BAND_UMTS_TDD",
        [18] = "IBI_NET_BAND_INVALID",
        [19] = "???",
        [20] = "???",
        [21] = "???",
        [22] = "???",
        [23] = "???",
        [24] = "???",
        [25] = "???",
        [26] = "???",
        [27] = "???",
        [28] = "???",
        [29] = "???",
        [30] = "???",
        [31] = "???",
        [32] = "???",
        [33] = "???",
        [34] = "???",
        [35] = "???",
        [36] = "???",
        [37] = "???",
        [38] = "???",
        [39] = "???",
        [40] = "???",
        [41] = "???",
        [42] = "???",
        [43] = "???",
        [44] = "???",
        [45] = "???",
        [46] = "???",
        [47] = "???",
        [48] = "???",
        [49] = "???",
        [50] = "IBI_NET_BAND_UMTS_I",
        [51] = "IBI_NET_BAND_UMTS_II",
        [52] = "IBI_NET_BAND_UMTS_III",
        [53] = "IBI_NET_BAND_UMTS_IV",
        [54] = "IBI_NET_BAND_UMTS_V",
        [55] = "IBI_NET_BAND_UMTS_VI",
        [56] = "IBI_NET_BAND_UMTS_VII",
        [57] = "IBI_NET_BAND_UMTS_VIII",
        [58] = "IBI_NET_BAND_UMTS_IX",
        [59] = "IBI_NET_BAND_UMTS_X",
        [60] = "IBI_NET_BAND_UMTS_XI",
        [61] = "IBI_NET_BAND_UMTS_XII",
        [62] = "IBI_NET_BAND_UMTS_XIII",
        [63] = "IBI_NET_BAND_UMTS_XIV",
        [64] = "IBI_NET_BAND_UMTS_XV",
        [65] = "IBI_NET_BAND_UMTS_XVI",
        [66] = "IBI_NET_BAND_UMTS_XVII",
        [67] = "IBI_NET_BAND_UMTS_XVIII",
        [68] = "IBI_NET_BAND_UMTS_XIX",
        [69] = "IBI_NET_BAND_UMTS_XX",
        [70] = "IBI_NET_BAND_UMTS_XXI",
        [71] = "IBI_NET_BAND_UMTS_XXII",
        [72] = "???",
        [73] = "???",
        [74] = "IBI_NET_BAND_UMTS_XXV",
        [75] = "IBI_NET_BAND_UMTS_INVALID",
        [76] = "???",
        [77] = "???",
        [78] = "???",
        [79] = "???",
        [80] = "???",
        [81] = "???",
        [82] = "???",
        [83] = "???",
        [84] = "???",
        [85] = "IBI_NET_BAND_UMTS_TDD_A",
        [86] = "IBI_NET_BAND_UMTS_TDD_B",
        [87] = "IBI_NET_BAND_UMTS_TDD_C",
        [88] = "IBI_NET_BAND_UMTS_TDD_D",
        [89] = "IBI_NET_BAND_UMTS_TDD_E",
        [90] = "IBI_NET_BAND_UMTS_TDD_F",
        [91] = "IBI_NET_BAND_UMTS_TDD_INVALID",
        [92] = "???",
        [93] = "???",
        [94] = "???",
        [95] = "???",
        [96] = "???",
        [97] = "???",
        [98] = "???",
        [99] = "???",
        [100] = "???",
        [101] = "IBI_NET_BAND_LTE_1",
        [102] = "IBI_NET_BAND_LTE_2",
        [103] = "IBI_NET_BAND_LTE_3",
        [104] = "IBI_NET_BAND_LTE_4",
        [105] = "IBI_NET_BAND_LTE_5",
        [106] = "IBI_NET_BAND_LTE_6",
        [107] = "IBI_NET_BAND_LTE_7",
        [108] = "IBI_NET_BAND_LTE_8",
        [109] = "IBI_NET_BAND_LTE_9",
        [110] = "IBI_NET_BAND_LTE_10",
        [111] = "IBI_NET_BAND_LTE_11",
        [112] = "IBI_NET_BAND_LTE_12",
        [113] = "IBI_NET_BAND_LTE_13",
        [114] = "IBI_NET_BAND_LTE_14",
        [115] = "IBI_NET_BAND_LTE_15",
        [116] = "IBI_NET_BAND_LTE_16",
        [117] = "IBI_NET_BAND_LTE_17",
        [118] = "IBI_NET_BAND_LTE_18",
        [119] = "IBI_NET_BAND_LTE_19",
        [120] = "IBI_NET_BAND_LTE_20",
        [121] = "IBI_NET_BAND_LTE_21",
        [122] = "IBI_NET_BAND_LTE_22",
        [123] = "IBI_NET_BAND_LTE_23",
        [124] = "IBI_NET_BAND_LTE_24",
        [125] = "IBI_NET_BAND_LTE_25",
        [126] = "IBI_NET_BAND_LTE_26",
        [127] = "IBI_NET_BAND_LTE_27",
        [128] = "IBI_NET_BAND_LTE_28",
        [129] = "IBI_NET_BAND_LTE_29",
        [130] = "IBI_NET_BAND_LTE_30",
        [131] = "IBI_NET_BAND_LTE_31",
        [132] = "???",
        [133] = "IBI_NET_BAND_LTE_33",
        [134] = "IBI_NET_BAND_LTE_34",
        [135] = "IBI_NET_BAND_LTE_35",
        [136] = "IBI_NET_BAND_LTE_36",
        [137] = "IBI_NET_BAND_LTE_37",
        [138] = "IBI_NET_BAND_LTE_38",
        [139] = "IBI_NET_BAND_LTE_39",
        [140] = "IBI_NET_BAND_LTE_40",
        [141] = "IBI_NET_BAND_LTE_41",
        [142] = "IBI_NET_BAND_LTE_42",
        [143] = "IBI_NET_BAND_LTE_43",
        [144] = "IBI_NET_BAND_LTE_44",
        [145] = "IBI_NET_BAND_LTE_INVALID",
        [146] = "IBI_NET_BAND_LTE_45",
        [147] = "IBI_NET_BAND_LTE_46",
        [148] = "???",
        [149] = "???",
        [150] = "???",
        [151] = "???",
        [152] = "???",
        [153] = "???",
        [154] = "???",
        [155] = "???",
        [156] = "???",
        [157] = "???",
        [158] = "???",
        [159] = "???",
        [160] = "???",
        [161] = "???",
        [162] = "???",
        [163] = "???",
        [164] = "???",
        [165] = "???",
        [166] = "IBI_NET_BAND_LTE_65",
        [167] = "IBI_NET_BAND_LTE_66",
        [168] = "IBI_NET_BAND_LTE_67",
        [169] = "IBI_NET_BAND_LTE_68",
        [170] = "???",
        [171] = "???",
        [172] = "IBI_NET_BAND_LTE_71",
        [173] = "???",
        [174] = "???",
        [175] = "???",
        [176] = "???",
        [177] = "???",
        [178] = "???",
        [179] = "???",
        [180] = "???",
        [181] = "???",
        [182] = "???",
        [183] = "???",
        [184] = "???",
        [185] = "???",
        [186] = "???",
        [187] = "???",
        [188] = "???",
        [189] = "???",
        [190] = "???",
        [191] = "???",
        [192] = "???",
        [193] = "???",
        [194] = "???",
        [195] = "???",
        [196] = "???",
        [197] = "???",
        [198] = "???",
        [199] = "???",
        [200] = "IBI_NET_BAND_CDMA_0",
        [201] = "IBI_NET_BAND_CDMA_1",
        [202] = "IBI_NET_BAND_CDMA_2",
        [203] = "IBI_NET_BAND_CDMA_3",
        [204] = "IBI_NET_BAND_CDMA_4",
        [205] = "IBI_NET_BAND_CDMA_5",
        [206] = "IBI_NET_BAND_CDMA_6",
        [207] = "IBI_NET_BAND_CDMA_7",
        [208] = "IBI_NET_BAND_CDMA_8",
        [209] = "IBI_NET_BAND_CDMA_9",
        [210] = "IBI_NET_BAND_CDMA_10",
        [211] = "IBI_NET_BAND_CDMA_11",
        [212] = "IBI_NET_BAND_CDMA_12",
        [213] = "IBI_NET_BAND_CDMA_13",
        [214] = "IBI_NET_BAND_CDMA_14",
        [215] = "IBI_NET_BAND_CDMA_15",
        [216] = "IBI_NET_BAND_CDMA_16",
        [217] = "IBI_NET_BAND_CDMA_17",
        [218] = "IBI_NET_BAND_CDMA_18",
        [219] = "IBI_NET_BAND_CDMA_19",
        [220] = "IBI_NET_BAND_CDMA_20",
        [221] = "IBI_NET_BAND_CDMA_21",
        [222] = "???",
        [223] = "???",
        [224] = "???",
        [225] = "???",
        [226] = "???",
        [227] = "???",
        [228] = "???",
        [229] = "???",
        [230] = "???",
        [231] = "???",
        [232] = "???",
        [233] = "???",
        [234] = "???",
        [235] = "???",
        [236] = "???",
        [237] = "???",
        [238] = "???",
        [239] = "???",
        [240] = "???",
        [241] = "???",
        [242] = "???",
        [243] = "???",
        [244] = "???",
        [245] = "???",
        [246] = "???",
        [247] = "???",
        [248] = "???",
        [249] = "???",
        [250] = "???",
        [251] = "???",
        [252] = "???",
        [253] = "???",
        [254] = "???",
        [255] = "IBI_NET_BAND_AUTOMATIC",
    },
    ["IBINetBandSelectionMode"] = {
        [0] = "IBI_NET_BAND_SELECTION_MODE_AUTOMATIC",
        [1] = "IBI_NET_BAND_SELECTION_MODE_MANUAL",
        [2] = "IBI_NET_BAND_SELECTION_MODE_CURRENT_CONFIGURATION",
    },
    ["IBINetCdmaChannel"] = {
        [0] = "IBI_CDMA_CHANNEL_TYPE_DEDICATED",
        [1] = "IBI_CDMA_CHANNEL_TYPE_COMMON_IF_DED_NOT_AVAIL",
        [2] = "IBI_CDMA_CHANNEL_TYPE_COMMON",
    },
    ["IBINetCellLteAcBarringStatusIndTrigger"] = {
        [1] = "IBI_NET_CELL_SIB2_BARRING_CONFIG",
        [0] = "IBI_NET_CELL_CALL_EST_BARRED_INFO",
    },
    ["IBINetCellType"] = {
        [0] = "IBI_NET_SERVING_CELL",
        [1] = "IBI_NET_NEIGBOURING_CELL",
    },
    ["IBINetConfigureNetworkModeError"] = {
        [0] = "IBI_NET_CONFIG_ERR_FEATURE_NOT_SUPPORTED",
        [1] = "IBI_NET_CONFIG_ERR_WRONG_PARAMS",
        [2] = "IBI_NET_CONFIG_ERR_RAT_CONFIGURATION",
        [3] = "IBI_NET_CONFIG_ERR_UEMOO_RAT_CONFLICT",
        [4] = "IBI_NET_CONFIG_ERR_BAND_2G_CONFIGURATION",
        [5] = "IBI_NET_CONFIG_ERR_BAND_3G_CONFIGURATION",
        [6] = "IBI_NET_CONFIG_ERR_BAND_3G_TDSCDMA_CONFIGURATION",
        [7] = "IBI_NET_CONFIG_ERR_BAND_4G_CONFIGURATION",
        [8] = "IBI_NET_CONFIG_ERR_VOLTE_CALL_ACTIVE",
        [9] = "IBI_NET_CONFIG_ERR_CS_CALL_ACTIVE",
        [10] = "IBI_NET_CONFIG_ERR_OTHER",
    },
    ["IBINetDcBarringFactor"] = {
        [0] = "IBI_NET_DC_BARRING_FACTOR_P00",
        [1] = "IBI_NET_DC_BARRING_FACTOR_P05",
        [2] = "IBI_NET_DC_BARRING_FACTOR_P10",
        [3] = "IBI_NET_DC_BARRING_FACTOR_P15",
        [4] = "IBI_NET_DC_BARRING_FACTOR_P20",
        [5] = "IBI_NET_DC_BARRING_FACTOR_P25",
        [6] = "IBI_NET_DC_BARRING_FACTOR_P30",
        [7] = "IBI_NET_DC_BARRING_FACTOR_P40",
        [8] = "IBI_NET_DC_BARRING_FACTOR_P50",
        [9] = "IBI_NET_DC_BARRING_FACTOR_P60",
        [10] = "IBI_NET_DC_BARRING_FACTOR_P70",
        [11] = "IBI_NET_DC_BARRING_FACTOR_P75",
        [12] = "IBI_NET_DC_BARRING_FACTOR_P80",
        [13] = "IBI_NET_DC_BARRING_FACTOR_P85",
        [14] = "IBI_NET_DC_BARRING_FACTOR_P90",
        [15] = "IBI_NET_DC_BARRING_FACTOR_P95",
        [16] = "IBI_NET_DC_BARRING_FACTOR_P100",
    },
    ["IBINetDcBarringTime"] = {
        [0] = "IBI_NET_DC_BARRING_TIME_S0",
        [1] = "IBI_NET_DC_BARRING_TIME_S4",
        [2] = "IBI_NET_DC_BARRING_TIME_S8",
        [3] = "IBI_NET_DC_BARRING_TIME_S16",
        [4] = "IBI_NET_DC_BARRING_TIME_S32",
        [5] = "IBI_NET_DC_BARRING_TIME_S64",
        [6] = "IBI_NET_DC_BARRING_TIME_S128",
        [7] = "IBI_NET_DC_BARRING_TIME_S256",
        [8] = "IBI_NET_DC_BARRING_TIME_S512",
    },
    ["IBINetDcImsRegistrationState"] = {
        [0] = "IBI_NET_DC_IMS_REGISTRATION_STATE_STARTED",
        [1] = "IBI_NET_DC_IMS_REGISTRATION_STATE_FAILURE",
        [2] = "IBI_NET_DC_IMS_REGISTRATION_STATE_RETRY",
        [3] = "IBI_NET_DC_IMS_REGISTRATION_STATE_SUCCESSFUL",
    },
    ["IBINetDcImsRegistrationStatus"] = {
        [1] = "IBI_NET_DC_IMS_STATUS_REGISTERED",
        [0] = "IBI_NET_DC_IMS_STATUS_NOT_REGISTERED",
    },
    ["IBINetDcImsRegistrationType"] = {
        [1] = "IBI_NET_DC_IMS_RE_REGISTRATION",
        [0] = "IBI_NET_DC_IMS_NEW_REGISTRATION",
    },
    ["IBINetDcImsServiceType"] = {
        [0] = "IBI_NET_DC_IMS_SERVICE_TYPE_VOICE",
        [1] = "IBI_NET_DC_IMS_SERVICE_TYPE_SMS",
        [2] = "IBI_NET_DC_IMS_SERVICE_TYPE_VOICE_SMS",
    },
    ["IBINetDcImsSessionStatus"] = {
        [1] = "IBI_NET_DC_IMS_SESSION_STOPPED",
        [0] = "IBI_NET_DC_IMS_SESSION_STARTED",
    },
    ["IBINetDcServiceDomain"] = {
        [0] = "IBI_NET_DC_SERVICE_DOMAIN_UNKNOWN",
        [1] = "IBI_NET_DC_SERVICE_DOMAIN_CS",
        [2] = "IBI_NET_DC_SERVICE_DOMAIN_IMS",
    },
    ["IBINetDcSsacBarringInfoResult"] = {
        [0] = "IBI_NET_DC_SSAC_BARRING_INFO_SUCCESS",
        [1] = "IBI_NET_DC_SSAC_BARRING_INFO_FAILURE_EUTRAN_NOT_ACTIVE",
    },
    ["IBINetDcVoiceDomainPreference"] = {
        [0] = "IBI_NET_DC_VOICE_DOMAIN_PREFERENCE_CS_ONLY",
        [1] = "IBI_NET_DC_VOICE_DOMAIN_PREFERENCE_IMS_ONLY",
        [2] = "IBI_NET_DC_VOICE_DOMAIN_PREFERENCE_CS_PREFERRED",
        [3] = "IBI_NET_DC_VOICE_DOMAIN_PREFERENCE_IMS_PREFERRED",
    },
    ["IBINetDuplexMode"] = {
        [0] = "IBI_NET_DUPLEX_MODE_CURRENT_CONFIGURATION",
        [1] = "IBI_NET_DUPLEX_MODE_FDD_TDD",
        [2] = "IBI_NET_DUPLEX_MODE_FDD",
        [3] = "IBI_NET_DUPLEX_MODE_TDD",
    },
    ["IBINetEmergencyCallType"] = {
        [0] = "IBI_NET_EM_CALL_TYPE_NONE",
        [1] = "IBI_NET_EM_CALL_TYPE_EM_SETUP_EM_CALL",
        [2] = "IBI_NET_EM_CALL_TYPE_NORMAL_SETUP_EM_CALL",
        [3] = "IBI_NET_EM_CALL_TYPE_T911",
        [4] = "IBI_NET_EM_CALL_TYPE_NOT_SELECTED_EM_CALL",
    },
    ["IBINetEmergencyCellInfoResult"] = {
        [0] = "IBI_NET_EMERGENCY_CELL_INFO_RESULT_SUCCESS",
        [1] = "IBI_NET_EMERGENCY_CELL_INFO_RESULT_FAILURE",
        [2] = "IBI_NET_EMERGENCY_CELL_INFO_RESULT_ABORTED",
        [3] = "IBI_NET_EMERGENCY_CELL_INFO_RESULT_ALREADY_REQUESTED",
    },
    ["IBINetEmergencyCellSearchFailCause"] = {
        [0] = "IBI_NET_EMERGENCY_CELL_SEARCH_FAIL_NO_CAUSE",
    },
    ["IBINetEmergencySearchModePref"] = {
        [0] = "IBI_NET_EMERGENCY_SEARCH_MODE_CS_OVER_PS",
        [1] = "IBI_NET_EMERGENCY_SEARCH_MODE_PS_OVER_CS",
        [2] = "IBI_NET_EMERGENCY_SEARCH_MODE_CS_ONLY",
        [3] = "IBI_NET_EMERGENCY_SEARCH_MODE_PS_ONLY",
    },
    ["IBINetEncodingScheme"] = {
        [1] = "IBI_NET_ENCODING_SCHEME_UCS2",
        [0] = "IBI_NET_ENCODING_SCHEME_ASCII",
    },
    ["IBINetEonsSupport"] = {
        [1] = "IBI_NET_EONS_SUPPORT_TRUE",
        [0] = "IBI_NET_EONS_SUPPORT_FALSE",
    },
    ["IBINetEvdoRevision"] = {
        [0] = "IBI_NET_EVDO_REV_0",
        [1] = "IBI_NET_EVDO_REV_A",
        [2] = "IBI_NET_EVDO_REV_B",
    },
    ["IBINetFdStatus"] = {
        [0] = "IBI_NET_DORMANCY_STATUS_DORMANT",
        [1] = "IBI_NET_DORMANCY_STATUS_ACTIVE",
        [2] = "IBI_NET_DORMANCY_STATUS_INVALID",
    },
    ["IBINetFdorRejectCause"] = {
        [0] = "IBI_NET_FD_DISCARD_CAUSE_DEFAULT",
        [1] = "IBI_NET_FD_DISCARD_CAUSE_T323_RUNNING",
        [2] = "IBI_NET_FD_DISCARD_CAUSE_WRONG_STATE",
        [3] = "IBI_NET_FD_DISCARD_CAUSE_NO_SIG_PS",
        [4] = "IBI_NET_FD_DISCARD_CAUSE_SIG_CS",
        [5] = "IBI_NET_FD_DISCARD_CAUSE_PROC_RUNNING",
        [6] = "IBI_NET_FD_DISCARD_CAUSE_NW_DEACT",
        [7] = "IBI_NET_FD_DISCARD_CAUSE_NAS_STOP",
        [8] = "IBI_NET_FD_DISCARD_CAUSE_PDCP_STOP",
        [9] = "IBI_NET_FD_DISCARD_CAUSE_RLC_STOP",
        [10] = "IBI_NET_FD_DISCARD_CAUSE_PEER_MSG",
        [11] = "IBI_NET_FD_DISCARD_CAUSE_NO_PS_RAB",
        [12] = "IBI_NET_FD_DISCARD_CAUSE_CELL_URA_PCH_V316_LIMIT",
        [13] = "IBI_NET_FD_DISCARD_CAUSE_EMERGENCY_CALL",
        [14] = "IBI_NET_FD_DISCARD_CAUSE_CALL_RE_EST",
        [15] = "IBI_NET_FD_DISCARD_CAUSE_TCH_F_NEEDED",
        [16] = "IBI_NET_FD_DISCARD_CAUSE_SPEECH_TCH_H",
        [17] = "IBI_NET_FD_DISCARD_CAUSE_DATA_TCH_H",
        [18] = "IBI_NET_FD_DISCARD_CAUSE_LOCATION_UPDATE",
        [19] = "IBI_NET_FD_DISCARD_CAUSE_ANSWER_TO_PAGING",
        [20] = "IBI_NET_FD_DISCARD_CAUSE_OTHER",
        [21] = "IBI_NET_FD_DISCARD_CAUSE_DTM_NOT_SUPPORT",
        [22] = "IBI_NET_FD_DISCARD_CAUSE_OR_CONV_CALL",
        [23] = "IBI_NET_FD_DISCARD_CAUSE_OR_STREAM_CALL",
        [24] = "IBI_NET_FD_DISCARD_CAUSE_OR_INTACT_CALL",
        [25] = "IBI_NET_FD_DISCARD_CAUSE_OR_BACKG_CALL",
        [26] = "IBI_NET_FD_DISCARD_CAUSE_OR_SUBTR_CALL",
        [27] = "IBI_NET_FD_DISCARD_CAUSE_TE_CONV_CALL",
        [28] = "IBI_NET_FD_DISCARD_CAUSE_TE_STREAM_CALL",
        [29] = "IBI_NET_FD_DISCARD_CAUSE_TE_INTACT_CALL",
        [30] = "IBI_NET_FD_DISCARD_CAUSE_TE_BACKG_CALL",
        [31] = "IBI_NET_FD_DISCARD_CAUSE_INT_RAT_CELL_SEL",
        [32] = "IBI_NET_FD_DISCARD_CAUSE_INT_RAT_CELL_CHG",
        [33] = "IBI_NET_FD_DISCARD_CAUSE_REGISTRATION",
        [34] = "IBI_NET_FD_DISCARD_CAUSE_DETACH",
        [35] = "IBI_NET_FD_DISCARD_CAUSE_OR_HIGH_PRIO",
        [36] = "IBI_NET_FD_DISCARD_CAUSE_OR_LOW_PRIO",
        [37] = "IBI_NET_FD_DISCARD_CAUSE_TE_HIGH_PRIO",
        [38] = "IBI_NET_FD_DISCARD_CAUSE_TE_LOW_PRIO",
        [39] = "IBI_NET_FD_DISCARD_CAUSE_RAT_NOT_UMTS",
        [40] = "IBI_NET_FD_DISCARD_CAUSE_AS_INACTIVE",
        [41] = "IBI_NET_FD_DISCARD_CAUSE_RR_NO_CONN",
        [42] = "IBI_NET_FD_DISCARD_CAUSE_PS_CONN_IND",
        [43] = "IBI_NET_URRC_FD_DISCARD_CAUSE_DATA_IN_BUFFER",
    },
    ["IBINetGetPlmnNameInfoResult"] = {
        [0] = "IBI_NET_PLMN_NAME_INFO_RESULT_SUCCESS",
        [1] = "IBI_NET_PLMN_NAME_INFO_RESULT_SIM_CACHING_ONGOING",
    },
    ["IBINetNetworkOpMode"] = {
        [0] = "IBI_NET_NETWORK_OP_MODE_NONE",
        [1] = "IBI_NET_NETWORK_OP_MODE_I",
        [2] = "IBI_NET_NETWORK_OP_MODE_II",
    },
    ["IBINetPlmnNameSource"] = {
        [0] = "IBI_NET_PLMN_NAME_SOURCE_SIM",
        [1] = "IBI_NET_PLMN_NAME_SOURCE_NETWORK",
        [2] = "IBI_NET_PLMN_NAME_SOURCE_MODEM",
        [3] = "IBI_NET_PLMN_NAME_SOURCE_NOT_FOUND",
    },
    ["IBINetRadioSignalReportingConfigType"] = {
        [0] = "IBI_NET_RADIO_SIGNAL_REPORTING_CONFIG_TYPE_NONE",
        [1] = "IBI_NET_RADIO_SIGNAL_REPORTING_CONFIG_TYPE_BAR_MAP",
        [2] = "IBI_NET_RADIO_SIGNAL_REPORTING_CONFIG_TYPE_THRESHOLD",
    },
    ["IBINetRegistrationMode"] = {
        [1] = "IBI_NET_REGISTRATION_MODE_MANUAL",
        [0] = "IBI_NET_REGISTRATION_MODE_AUTOMATIC",
    },
    ["IBINetRegistrationRejectCause"] = {
        [0] = "IBI_NET_REGISTRATION_REJECT_CAUSE_NOT_REGISTERED",
        [1] = "IBI_NET_REGISTRATION_REJECT_CAUSE_INVALID_SIM",
        [2] = "IBI_NET_REGISTRATION_REJECT_CAUSE_N_REG_REQ",
        [3] = "IBI_NET_REGISTRATION_REJECT_CAUSE_NO_CELL",
        [4] = "IBI_NET_REGISTRATION_REJECT_CAUSE_NO_CARRIER",
        [5] = "IBI_NET_REGISTRATION_REJECT_CAUSE_PLMN_SEARCH",
        [6] = "IBI_NET_REGISTRATION_REJECT_CAUSE_PLMN_SEARCH_ENDED",
        [7] = "IBI_NET_REGISTRATION_REJECT_CAUSE_AUTH_FAILURE",
        [8] = "IBI_NET_REGISTRATION_REJECT_CAUSE_POWER_DOWN",
        [9] = "IBI_NET_REGISTRATION_REJECT_CAUSE_FORB_PLMN",
        [10] = "IBI_NET_REGISTRATION_REJECT_CAUSE_FORB_LAI",
        [11] = "IBI_NET_REGISTRATION_REJECT_CAUSE_DETACHED",
        [12] = "IBI_NET_REGISTRATION_REJECT_CAUSE_DISABLED",
        [13] = "IBI_NET_REGISTRATION_REJECT_CAUSE_INVALID_PARAMETER",
        [14] = "IBI_NET_REGISTRATION_REJECT_CAUSE_REJ_BY_NETWORK",
        [15] = "IBI_NET_REGISTRATION_REJECT_CAUSE_INTERNAL_FAILURE",
        [16] = "IBI_NET_REGISTRATION_REJECT_CAUSE_ATTACH_TEMP_BARRED",
        [17] = "IBI_NET_REGISTRATION_REJECT_CAUSE_NO_CAUSE",
        [18] = "IBI_NET_REGISTRATION_REJECT_CAUSE_ATTACH_NOT_ALLOWED",
        [19] = "IBI_NET_REGISTRATION_REJECT_CAUSE_REGISTRATION_IN_PROGRESS",
        [20] = "IBI_NET_REGISTRATION_REJECT_CAUSE_USER_ABORT",
        [21] = "IBI_NET_REGISTRATION_REJECT_CAUSE_DUAL_SIM_CONFLICT",
        [22] = "IBI_NET_REGISTRATION_REJECT_CAUSE_NO_CARRIER_DUAL_SIM_CONFLICT",
        [23] = "IBI_NET_REGISTRATION_REJECT_CAUSE_CSG_UNAUTHORIZED",
    },
    ["IBINetRegistrationStatus"] = {
        [0] = "IBI_NET_REGISTRATION_STATUS_NORMAL_SERVICE",
        [1] = "IBI_NET_REGISTRATION_STATUS_FAILURE",
        [2] = "IBI_NET_REGISTRATION_STATUS_LIMITED_SERVICE",
        [3] = "IBI_NET_REGISTRATION_STATUS_NO_SERVICE",
        [4] = "IBI_NET_REGISTRATION_STATUS_AT_NOT_REGISTERED",
        [5] = "IBI_NET_REGISTRATION_STATUS_SERVICE_DISABLED",
        [6] = "IBI_NET_REGISTRATION_STATUS_SERVICE_DETACHED",
        [7] = "IBI_NET_REGISTRATION_STATUS_PS_EMERGENCY",
        [8] = "IBI_NET_REGISTRATION_STATUS_PS_EMERGENCY_LIMITED",
        [9] = "IBI_NET_REGISTRATION_STATUS_REGISTERED_SMS_ONLY",
        [10] = "IBI_NET_REGISTRATION_STATUS_REGISTRATION_IN_PROGRESS",
    },
    ["IBINetSingleShotReportingReqType"] = {
        [1] = "IBI_NET_FRESH_SERV_CACHED_NEIGH_CELL_MEAS",
        [0] = "IBI_NET_CACHED_MEAS",
    },
    ["IBINetTimerId"] = {
        [1] = "IBI_NET_TIMER_T3402",
    },
    ["IBINetUserCause"] = {
        [0] = "IBI_NET_USER_CAUSE_POWER_DOWN",
        [1] = "IBI_NET_USER_CAUSE_INVALID_SIM",
        [2] = "IBI_NET_USER_CAUSE_NOT_ALLOWED",
        [3] = "IBI_NET_USER_CAUSE_ABORT_BY_USER",
        [4] = "IBI_NET_USER_CAUSE_NOT_POSSIBLE",
        [5] = "IBI_NET_USER_CAUSE_DISABLE_SERVICE",
        [6] = "IBI_NET_USER_CAUSE_DETACH_SERVICE",
        [7] = "IBI_NET_USER_CAUSE_ATTACH_SERVICE",
        [8] = "IBI_NET_USER_CAUSE_ENABLE_SERVICE",
        [9] = "IBI_NET_USER_CAUSE_USER_RESELECTION",
        [10] = "IBI_NET_USER_CAUSE_AIRPLANE_MODE",
        [11] = "IBI_NET_USER_CAUSE_DEACTIVATE_STACK",
        [12] = "IBI_NET_USER_CAUSE_FAST_DETACH",
        [13] = "IBI_NET_USER_CAUSE_DUAL_SIM_CONFLICT",
    },
    ["IBIOtaspStatus"] = {
        [0] = "IBI_OTASP_STATUS_SPL_UNLOCKED",
        [1] = "IBI_OTASP_STATUS_SPC_RETRIES_EXCEEDED",
        [2] = "IBI_OTASP_STATUS_AKEY_EXCHANGED",
        [3] = "IBI_OTASP_STATUS_SSD_UPDATED",
        [4] = "IBI_OTASP_STATUS_NAM_DOWNLOADED",
        [5] = "IBI_OTASP_STATUS_MDN_DOWNLOADED",
        [6] = "IBI_OTASP_STATUS_IMSI_DOWNLOADED",
        [7] = "IBI_OTASP_STATUS_PRL_DOWNLOADED",
        [8] = "IBI_OTASP_STATUS_COMMITTED",
        [9] = "IBI_OTASP_STATUS_OTAPA_STARTED",
        [10] = "IBI_OTASP_STATUS_OTAPA_STOPPED",
        [11] = "IBI_OTASP_STATUS_OTAPA_ABORTED",
    },
    ["IBIPriGriWriteResp"] = {
        [0] = "IBI_PRI_GRI_STATUS_NOERR",
        [1] = "IBI_PRI_GRI_STATUS_WRITE_FAILED_INTERNAL",
        [2] = "IBI_PRI_GRI_STATUS_WRITE_FAILED_BB_REBOOT_REQD",
        [3] = "IBI_PRI_GRI_STATUS_WRITE_FAILED_BB_AIRPLANE_TOGGLE",
        [4] = "IBI_PRI_GRI_STATUS_INPUT_CHECK_FAILED",
        [5] = "IBI_PRI_GRI_STATUS_FILE_SIZE_TOO_BIG",
        [6] = "IBI_PRI_GRI_STATUS_FILER_REG_ERR",
        [7] = "IBI_PRI_GRI_STATUS_IBI_WRITE_SUCCESS",
        [8] = "IBI_PRI_STATUS_WRITE_NOT_ALLOWED_BY_NW_POLICE",
        [9] = "IBI_PRI_STATUS_SIGN_REJ_BY_SECURITY",
        [10] = "???",
        [11] = "???",
        [12] = "???",
        [13] = "???",
        [14] = "IBI_PRI_GRI_STATUS_WRITE_SUCCESS_BB_REBOOT_REQD",
        [15] = "IBI_PRI_GRI_STATUS_WRITE_SUCCESS_BB_AIRPLANE_TOGGLE",
    },
    ["IBIRat"] = {
        [0] = "IBI_RAT_NOT_AVAILABLE",
        [1] = "IBI_RAT_GSM",
        [2] = "IBI_RAT_UMTS",
        [3] = "IBI_RAT_LTE",
        [4] = "IBI_RAT_CDMA_1x",
        [5] = "IBI_RAT_CDMA_EVDO",
        [6] = "IBI_RAT_HYBRID_1xEVDO",
        [7] = "IBI_RAT_SRLTE_1xLTE",
    },
    ["IBIRatInfoExtension"] = {
        [1] = "IBI_RAT_INFO_EXT_TDD",
        [0] = "IBI_RAT_INFO_EXT_NO_INFORMATION",
    },
    ["IBIRatSwitchStatus"] = {
        [0] = "AP_RAT_SWITCH_ON",
        [1] = "AP_RAT_SWITCH_OFF",
        [2] = "AP_RAT_SWITCH_MAX",
    },
    ["IBIRatSwitchType"] = {
        [0] = "AP_LTE_RAT_SWITCH",
        [1] = "AP_3G_RAT_SWITCH",
        [2] = "AP_RAT_SWITCH_TYPE_MAX",
    },
    ["IBIRfPort"] = {
        [2] = "IBI_RF_PORTB_FCM1",
        [1] = "IBI_RF_PORTA_BCM",
    },
    ["IBIRfPortMapStatus"] = {
        [0] = "IBI_RF_PORTMAP_OK",
        [1] = "IBI_RF_PORTMAP_INVALID_PARAM",
    },
    ["IBIRfRat"] = {
        [0] = "IBI_RF_RAT_NOT_AVAILABLE",
        [1] = "IBI_RF_RAT_GSM",
        [2] = "IBI_RF_RAT_UMTS",
        [3] = "IBI_RF_RAT_LTE",
    },
    ["IBISimAccessAppType"] = {
        [0] = "IBI_SIM_ACCESS_APP_TYPE_UNKNOWN",
        [1] = "IBI_SIM_ACCESS_APP_TYPE_USIM",
        [2] = "IBI_SIM_ACCESS_APP_TYPE_ISIM",
        [3] = "IBI_SIM_ACCESS_APP_TYPE_CSIM",
        [4] = "IBI_SIM_ACCESS_APP_TYPE_GSM",
        [5] = "IBI_SIM_ACCESS_APP_TYPE_RUIM",
    },
    ["IBISimAccessCardType"] = {
        [0] = "IBI_SIM_ACCESS_NO_SIM_TYPE",
        [1] = "IBI_SIM_ACCESS_2GSIM_TYPE",
        [2] = "IBI_SIM_ACCESS_USIM_TYPE",
    },
    ["IBISimApduCmdResultType"] = {
        [0] = "IBI_SIM_APDU_CMD_SUCCESS",
        [1] = "IBI_SIM_APDU_CMD_SUCCESS_PROACTIVE_CMD_PENDING",
        [2] = "IBI_SIM_APDU_CMD_SUCCESS_DATA_TRANSFER_ONGOING",
        [3] = "IBI_SIM_APDU_CMD_SUCCESS_SIM_DATA_DOWNLOAD_ERROR",
        [4] = "IBI_SIM_APDU_CMD_SUCCESS_SIM_RESPONSE",
        [5] = "IBI_SIM_APDU_CMD_STK_BUSY",
        [6] = "IBI_SIM_APDU_CMD_NO_INFO_GIVEN_TYPE1",
        [7] = "IBI_SIM_APDU_CMD_RETURN_DATA_CORRUPTED",
        [8] = "IBI_SIM_APDU_CMD_EOF_REACHED",
        [9] = "IBI_SIM_APDU_CMD_SELECTED_FILE_INVALIDATED",
        [10] = "IBI_SIM_APDU_CMD_SELECTED_FILE_IN_TERMINATION_STATE",
        [11] = "IBI_SIM_APDU_CMD_MORE_DATA_AVAILABLE",
        [12] = "IBI_SIM_APDU_CMD_MORE_DATA_AVAILABLE_PROACTIVE_CMD_PENDING",
        [13] = "IBI_SIM_APDU_CMD_RESPONSE_DATA_AVAILABLE",
        [14] = "IBI_SIM_APDU_CMD_MORE_DATA_EXPECTED",
        [15] = "IBI_SIM_APDU_CMD_MORE_DATA_EXPECTED_PROACTIVE_CMD_PENDING",
        [16] = "IBI_SIM_APDU_CMD_SUCCESSFULL_BUT_RETRY",
        [17] = "IBI_SIM_APDU_CMD_NO_INFO_NONVOLATILE_MEM_UNCHANGED",
        [18] = "IBI_SIM_APDU_CMD_NO_INFO_NONVOLATILE_MEM_CHANGED",
        [19] = "IBI_SIM_APDU_CMD_MEMORY_PROBLEM",
        [20] = "IBI_SIM_APDU_CMD_WRONG_LENGTH",
        [21] = "IBI_SIM_APDU_CMD_WRONG_PARAMETER",
        [22] = "IBI_SIM_APDU_CMD_INS_NOT_SUPPORTED",
        [23] = "IBI_SIM_APDU_CMD_CLS_NOT_SUPPORTED",
        [24] = "IBI_SIM_APDU_CMD_TECHNICAL_PROBLEM",
        [25] = "IBI_SIM_APDU_CMD_NO_INFO_GIVEN_TYPE2",
        [26] = "IBI_SIM_APDU_CMD_LOGICAL_CHANNEL_NOT_SUPPORTED",
        [27] = "IBI_SIM_APDU_CMD_SECURE_MESSAGING_NOT_SUPPORTED",
        [28] = "IBI_SIM_APDU_CMD_NO_INFO_GIVEN_TYPE3",
        [29] = "IBI_SIM_APDU_CMD_INCOMPATIBLE_WITH_FILE_STRUCTURE",
        [30] = "IBI_SIM_APDU_CMD_SEC_STATUS_NOT_SATISFIED",
        [31] = "IBI_SIM_APDU_CMD_AUTH_BLOCKED",
        [32] = "IBI_SIM_APDU_CMD_REF_DATA_INVALIDATED",
        [33] = "IBI_SIM_APDU_CMD_COND_OF_USE_NOT_SATISFIED",
        [34] = "IBI_SIM_APDU_CMD_NOT_ALLOWED_NO_EF_SELECTED",
        [35] = "IBI_SIM_APDU_CMD_SEC_NOT_SATISFIED",
        [36] = "IBI_SIM_APDU_CMD_INCORRECT_PARAM_IN_DATA_FIELD",
        [37] = "IBI_SIM_APDU_CMD_FUNCTION_NOT_SUPPORTED",
        [38] = "IBI_SIM_APDU_CMD_FILE_NOT_FOUND",
        [39] = "IBI_SIM_APDU_CMD_RECORD_NOT_FOUND",
        [40] = "IBI_SIM_APDU_CMD_NOT_ENOUGH_MEM_SPACE",
        [41] = "IBI_SIM_APDU_CMD_INCORRECT_P1_P2",
        [42] = "IBI_SIM_APDU_CMD_INCONSISTENT_LC",
        [43] = "IBI_SIM_APDU_CMD_REF_DATA_NOT_FOUND",
        [44] = "IBI_SIM_APDU_CMD_INCREASE_CANNOT_BE_PERFORMED_MAX_VAL_REACHED",
        [45] = "IBI_SIM_APDU_CMD_AUTH_ERROR_APPLICATION_SPECIFIC",
        [46] = "IBI_SIM_APDU_CMD_SECURITY_SESSION_EXPIRED",
        [47] = "IBI_SIM_APDU_CMD_AUTH_ERROR_SECURITY_CONTEXT_NOT_SUPPORTED",
        [48] = "IBI_SIM_APDU_CMD_OTHER",
    },
    ["IBISimApplicationActivity"] = {
        [0] = "IBI_SIM_APPLICATION_SELECT_DF_NAME",
        [1] = "IBI_SIM_APPLICATION_SELECT_PART_NAME_FIRST",
        [2] = "IBI_SIM_APPLICATION_SELECT_PART_NAME_LAST",
        [3] = "IBI_SIM_APPLICATION_SELECT_PART_NAME_NEXT",
        [4] = "IBI_SIM_APPLICATION_SELECT_PART_NAME_PREV",
        [5] = "IBI_SIM_APPLICATION_SELECT_GSM",
        [6] = "IBI_SIM_APPLICATION_ACTIVATE",
        [7] = "IBI_SIM_APPLICATION_SHUTDOWN_INITIATED",
        [8] = "IBI_SIM_APPLICATION_DEACTIVATE",
        [9] = "IBI_SIM_APPLICATION_DEACTIVATE_CLOSE_CHANNEL",
        [10] = "IBI_SIM_APPLICATION_INFO",
    },
    ["IBISimAuthResult"] = {
        [0] = "IBI_SIM_AUTH_RESULT_SUCCESS",
        [1] = "IBI_SIM_AUTH_RESULT_SYNC_FAILURE",
        [2] = "IBI_SIM_AUTH_RESULT_MAC_ERROR",
        [3] = "IBI_SIM_AUTH_RESULT_SIM_ERROR",
        [4] = "IBI_SIM_AUTH_RESULT_CONTEXT_NOT_SUPPORTED",
        [5] = "IBI_SIM_AUTH_RESULT_WRONG_INPUT",
        [6] = "IBI_SIM_ATUH_RESULT_SIM_RESPONSE_ERROR",
    },
    ["IBISimCardType"] = {
        [1] = "IBI_SIM_CARD_TYPE_3G",
        [0] = "IBI_SIM_CARD_TYPE_2G",
    },
    ["IBISimChvStatus"] = {
        [0] = "IBI_SIM_NOT_AVAILABLE",
        [1] = "IBI_SIM_NEEDED",
        [2] = "IBI_SIM_NOT_NEEDED",
        [3] = "IBI_SIM_BLOCKED",
        [4] = "IBI_SIM_UNBLOCKING_BLOCKED",
        [5] = "IBI_SIM_VERIFIED",
        [6] = "IBI_SIM_REJECTED",
        [7] = "IBI_SIM_IN_CONTRADICTION_WITH_CHV_STATUS",
    },
    ["IBISimEfAccessErrorCause"] = {
        [0] = "IBI_SIM_RES_TYPE_ERROR_CAUSE_NONE",
        [1] = "IBI_SIM_RES_TYPE_WRONG_CID",
        [2] = "IBI_SIM_RES_TYPE_NO_MEM_FOR_RESP",
        [3] = "IBI_SIM_RES_TYPE_NO_FREE_UICC_CHANNEL",
        [4] = "IBI_SIM_RES_TYPE_EXT_FAILURE",
        [5] = "IBI_SIM_RES_EXT_CARD_SESSION_CLOSED",
        [6] = "IBI_SIM_CMD_STK_BUSY",
        [7] = "IBI_SIM_CMD_NO_INFO_GIVEN_TYPE1",
        [8] = "IBI_SIM_CMD_RETURN_DATA_CORRUPTED",
        [9] = "IBI_SIM_CMD_EOF_REACHED",
        [10] = "IBI_SIM_CMD_SELECTED_FILE_INVALIDATED",
        [11] = "IBI_SIM_CMD_SELECTED_FILE_IN_TERMINATION_STATE",
        [12] = "IBI_SIM_CMD_MORE_DATA_AVAILABLE",
        [13] = "IBI_SIM_CMD_MORE_DATA_AVAILABLE_PROACTIVE_CMD_PENDING",
        [14] = "IBI_SIM_CMD_RESPONSE_DATA_AVAILABLE",
        [15] = "IBI_SIM_CMD_MORE_DATA_EXPECTED",
        [16] = "IBI_SIM_CMD_MORE_DATA_EXPECTED_PROACTIVE_CMD_PENDING",
        [17] = "IBI_SIM_CMD_SUCCESSFULL_BUT_RETRY",
        [18] = "IBI_SIM_CMD_NO_INFO_NONVOLATILE_MEM_UNCHANGED",
        [19] = "IBI_SIM_CMD_NO_INFO_NONVOLATILE_MEM_CHANGED",
        [20] = "IBI_SIM_CMD_MEMORY_PROBLEM",
        [21] = "IBI_SIM_CMD_WRONG_LENGTH",
        [22] = "IBI_SIM_CMD_WRONG_PARAMETER",
        [23] = "IBI_SIM_CMD_INS_NOT_SUPPORTED",
        [24] = "IBI_SIM_CMD_CLS_NOT_SUPPORTED",
        [25] = "IBI_SIM_CMD_TECHNICAL_PROBLEM",
        [26] = "IBI_SIM_CMD_NO_INFO_GIVEN_TYPE2",
        [27] = "IBI_SIM_CMD_LOGICAL_CHANNEL_NOT_SUPPORTED",
        [28] = "IBI_SIM_CMD_SECURE_MESSAGING_NOT_SUPPORTED",
        [29] = "IBI_SIM_CMD_NO_INFO_GIVEN_TYPE3",
        [30] = "IBI_SIM_CMD_INCOMPATIBLE_WITH_FILE_STRUCTURE",
        [31] = "IBI_SIM_CMD_SEC_STATUS_NOT_SATISFIED",
        [32] = "IBI_SIM_CMD_AUTH_BLOCKED",
        [33] = "IBI_SIM_CMD_REF_DATA_INVALIDATED",
        [34] = "IBI_SIM_CMD_COND_OF_USE_NOT_SATISFIED",
        [35] = "IBI_SIM_CMD_NOT_ALLOWED_NO_EF_SELECTED",
        [36] = "IBI_SIM_CMD_SEC_NOT_SATISFIED",
        [37] = "IBI_SIM_CMD_INCORRECT_PARAM_IN_DATA_FIELD",
        [38] = "IBI_SIM_CMD_FUNCTION_NOT_SUPPORTED",
        [39] = "IBI_SIM_CMD_FILE_NOT_FOUND",
        [40] = "IBI_SIM_CMD_RECORD_NOT_FOUND",
        [41] = "IBI_SIM_CMD_NOT_ENOUGH_MEM_SPACE",
        [42] = "IBI_SIM_CMD_INCORRECT_P1_P2",
        [43] = "IBI_SIM_CMD_INCONSISTENT_LC",
        [44] = "IBI_SIM_CMD_REF_DATA_NOT_FOUND",
        [45] = "IBI_SIM_CMD_INCREASE_CANNOT_BE_PERFORMED_MAX_VAL_REACHED",
        [46] = "IBI_SIM_CMD_AUTH_ERROR_APPLICATION_SPECIFIC",
        [47] = "IBI_SIM_CMD_SECURITY_SESSION_EXPIRED",
        [48] = "IBI_SIM_CMD_OTHER",
    },
    ["IBISimEfAccessResType"] = {
        [0] = "IBI_SIM_RES_TYPE_OK",
        [1] = "IBI_SIM_RES_TYPE_FAIL",
    },
    ["IBISimEfType"] = {
        [0] = "IBI_SIM_UNKNOWN_FILE",
        [1] = "IBI_SIM_TRANSPARENT_FILE",
        [2] = "IBI_SIM_LINEAR_FIXED_FILE",
        [3] = "IBI_SIM_CYCLIC_FILE",
    },
    ["IBISimErrorCause"] = {
        [0] = "IBI_SIM_ERROR_CAUSE_UNKNOWN",
        [1] = "IBI_SIM_ERROR_CAUSE_BROKEN_SIM",
        [2] = "IBI_SIM_ERROR_CAUSE_EMPTY_TRAY",
    },
    ["IBISimFcpAppPinStatus"] = {
        [1] = "IBI_SIM_FCP_APP_PIN_ENABLED",
        [0] = "IBI_SIM_FCP_APP_PIN_DISABLED",
    },
    ["IBISimFcpFileStatus"] = {
        [0] = "IBI_SIM_FCP_FILE_STATUS_DEACTIVATED",
        [1] = "IBI_SIM_FCP_FILE_STATUS_ACTIVATED",
        [2] = "IBI_SIM_FCP_FILE_STATUS_RU_INVAL",
    },
    ["IBISimFcpSecAttrAccessCondtion"] = {
        [0] = "IBI_SIM_SEC_ATTR_ACCESS_CONDITION_NEVER",
        [1] = "IBI_SIM_SEC_ATTR_ACCESS_CONDITION_ALWAYS",
        [2] = "IBI_SIM_SEC_ATTR_ACCESS_CONDITION_OR_PIN",
        [3] = "IBI_SIM_SEC_ATTR_ACCESS_CONDITION_AND_PIN",
        [4] = "IBI_SIM_SEC_ATTR_ACCESS_CONDITION_PIN",
        [5] = "IBI_SIM_SEC_ATTR_ACCESS_CONDITION_ADM",
    },
    ["IBISimFcpSecAttrRefType"] = {
        [1] = "IBI_SIM_FCP_SEC_ATTR_REF_TYPE_SEID_RECS",
        [0] = "IBI_SIM_FCP_SEC_ATTR_REF_TYPE_REC",
    },
    ["IBISimFcpSecAttrType"] = {
        [0] = "IBI_SIM_FCP_SEC_ATTR_NONE",
        [1] = "IBI_SIM_FCP_SEC_ATTR_COMPACT",
        [2] = "IBI_SIM_FCP_SEC_ATTR_EXPANDED",
        [3] = "IBI_SIM_FCP_SEC_ATTR_REFERENCE",
    },
    ["IBISimFcpSfiType"] = {
        [0] = "IBI_SIM_FCP_SFI_TYPE_SPECIFIED_BY_FILE_ID",
        [1] = "IBI_SIM_FCP_SFI_TYPE_NOT_SUPPORTED",
        [2] = "IBI_SIM_FCP_SFI_TYPE_PRESENT",
    },
    ["IBISimFileType"] = {
        [0] = "IBI_SIM_RFU_TYPE",
        [1] = "IBI_SIM_EF_TYPE",
        [2] = "IBI_SIM_ADF_TYPE",
        [3] = "IBI_SIM_DF_TYPE",
        [4] = "IBI_SIM_BER_TLV_TYPE",
        [5] = "IBI_SIM_MF_TYPE",
    },
    ["IBISimGenPinResType"] = {
        [0] = "IBI_SIM_GEN_PIN_RES_TYPE_OK",
        [1] = "IBI_SIM_GEN_PIN_RES_TYPE_WRONG_PIN_VAL",
        [2] = "IBI_SIM_GEN_PIN_RES_TYPE_SIM_ERROR",
    },
    ["IBISimGenResType"] = {
        [0] = "IBI_SIM_GEN_RES_TYPE_OK",
        [1] = "IBI_SIM_GEN_RES_TYPE_WRONG_CID",
        [2] = "IBI_SIM_GEN_RES_TYPE_NO_MEM_FOR_RESP",
        [3] = "IBI_SIM_GEN_RES_TYPE_NO_FREE_UICC_CHANNEL",
        [4] = "IBI_SIM_GEN_RES_TYPE_FAILURE",
    },
    ["IBISimHwEvent"] = {
        [0] = "IBI_SIM_HW_EVENT_UNKNOWN",
        [1] = "IBI_SIM_HW_EVENT_INOUT_EDGE_DETECT_IN",
        [2] = "IBI_SIM_HW_EVENT_INOUT_EDGE_DETECT_OUT",
        [3] = "IBI_SIM_HW_EVENT_INOUT_DEBOUNCE_TIMEOUT",
        [4] = "IBI_SIM_HW_EVENT_INOUT_INSERTED",
        [5] = "IBI_SIM_HW_EVENT_INOUT_REMOVED",
    },
    ["IBISimPbCacheStatus"] = {
        [0] = "IBI_SIM_PB_SIM_PHONEBOOK_CACHE_STARTED",
        [1] = "IBI_SIM_PB_SIM_PHONEBOOK_CACHE_FINISHED",
    },
    ["IBISimPbLinkType"] = {
        [0] = "IBI_SIM_PB_LINK_TYPE_NO_LINK",
        [1] = "IBI_SIM_PB_LINK_TYPE_TYPE_1_LINK",
        [2] = "IBI_SIM_PB_LINK_TYPE_TYPE_2_LINK",
        [3] = "IBI_SIM_PB_LINK_TYPE_TYPE_3_LINK",
    },
    ["IBISimPbLocationInfo"] = {
        [0] = "IBI_SIM_PB_PB_NOT_SELECTED",
        [1] = "IBI_SIM_PB_SIM_PB",
        [2] = "IBI_SIM_PB_GLOBAL_PB",
        [3] = "IBI_SIM_PB_APPLICATION_PB",
    },
    ["IBISimPbResult"] = {
        [0] = "IBI_SIM_PB_RESULT_SUCCESS",
        [1] = "IBI_SIM_PB_RESULT_ERROR_PARAMETERS",
        [2] = "IBI_SIM_PB_RESULT_ERROR_ACCESS",
        [3] = "IBI_SIM_PB_RESULT_ERROR_EXT_MEMORY_EXCEEDED",
        [4] = "IBI_SIM_PB_RESULT_ERROR_SIM_ERROR",
        [5] = "IBI_SIM_PB_RESULT_ERROR_CACHE_LOAD_NOT_FINISHED",
        [6] = "IBI_SIM_PB_RESULT_ERROR_USIM_PB_NOT_PRESENT",
        [7] = "IBI_SIM_PB_RESULT_ERROR_USIM_PB_NOT_SELECTED",
        [8] = "IBI_SIM_PB_RESULT_ERROR_USIM_PB_NOT_READY",
        [9] = "IBI_SIM_PB_RESULT_ERROR_OPERATION_NOT_ALLOWED",
        [10] = "IBI_SIM_PB_RESULT_ERROR_EXT_MEMORY_FAILURE",
        [11] = "IBI_SIM_PB_RESULT_ERROR_SIM_BUSY",
        [12] = "IBI_SIM_PB_RESULT_ERROR_ADN_MEMORY_EXCEEDED",
        [13] = "IBI_SIM_PB_RESULT_ERROR_ANR_MEMORY_EXCEEDED",
        [14] = "IBI_SIM_PB_RESULT_ERROR_SNE_MEMORY_EXCEEDED",
        [15] = "IBI_SIM_PB_RESULT_ERROR_EMAIL_MEMORY_EXCEEDED",
        [16] = "IBI_SIM_PB_RESULT_ERROR_UNSUCCESSFUL",
        [17] = "IBI_SIM_PB_RESULT_ERROR_MEM_RETRY_SUCCESS",
        [18] = "IBI_SIM_PB_RESULT_ERROR_MEMORY_ERROR",
        [19] = "IBI_SIM_PB_RESULT_ERROR_TOOLKIT_BUSY",
        [20] = "IBI_SIM_PB_RESULT_ERROR_NO_EF_CHOOSEN",
        [21] = "IBI_SIM_PB_RESULT_ERROR_INVALID_ADDRESS",
        [22] = "IBI_SIM_PB_RESULT_ERROR_REFERENCE_ERROR",
        [23] = "IBI_SIM_PB_RESULT_ERROR_INCONSISTENT_CMD",
        [24] = "IBI_SIM_PB_RESULT_ERROR_NO_CHV_INITIALIZED",
        [25] = "IBI_SIM_PB_RESULT_ERROR_SECURITY_ERROR",
        [26] = "IBI_SIM_PB_RESULT_ERROR_CONTRADICT_WITH_CHV_STATE",
        [27] = "IBI_SIM_PB_RESULT_ERROR_CONTRADICT_INVALID_STATE",
        [28] = "IBI_SIM_PB_RESULT_ERROR_NO_ATTEMPT_LEFT",
        [29] = "IBI_SIM_PB_RESULT_ERROR_MAX_VALUE_REACHED",
        [30] = "IBI_SIM_PB_RESULT_ERROR_TOOLKIT_RESPONSE_ERROR",
        [31] = "IBI_SIM_PB_RESULT_ERROR_APPLICATION_ERROR_P3",
        [32] = "IBI_SIM_PB_RESULT_ERROR_APPLICATION_ERROR_P1P2",
        [33] = "IBI_SIM_PB_RESULT_ERROR_UNKNOWN_INSTRUCTION",
        [34] = "IBI_SIM_PB_RESULT_ERROR_WRONG_INSTRUCTION_CLASS",
        [35] = "IBI_SIM_PB_RESULT_ERROR_TECHNICAL_PROBLEM",
        [36] = "IBI_SIM_PB_RESULT_ERROR_APPLICATION_ERROR",
        [37] = "IBI_SIM_PB_RESULT_ERROR_UNKNOWN",
    },
    ["IBISimPbUsimPbLocation"] = {
        [0] = "IBI_SIM_PB_USIM_PB_LOC_NONE",
        [1] = "IBI_SIM_PB_USIM_PB_LOC_GLOBAL",
        [2] = "IBI_SIM_PB_USIM_PB_LOC_LOCAL",
    },
    ["IBISimPinActivity"] = {
        [0] = "IBI_SIM_PIN_ACTIVITY_VERIFY",
        [1] = "IBI_SIM_PIN_ACTIVITY_UNBLOCK",
        [2] = "IBI_SIM_PIN_ACTIVITY_DISABLE",
        [3] = "IBI_SIM_PIN_ACTIVITY_ENABLE",
        [4] = "IBI_SIM_PIN_ACTIVITY_CHANGE",
        [5] = "IBI_SIM_PIN_ACTIVITY_SUBSTITUTE",
        [6] = "IBI_SIM_PIN_ACTIVITY_REMAINING_ATTEMPTS",
        [7] = "IBI_SIM_PIN_ACTIVITY_DUMMY_VERIFY",
    },
    ["IBISimPinStatus"] = {
        [0] = "IBI_SIM_PIN_NOT_AVAILABLE",
        [1] = "IBI_SIM_PIN_VERIFICATION_NEEDED",
        [2] = "IBI_SIM_PIN_VERIFICATION_NOT_NEEDED",
        [3] = "IBI_SIM_PIN_BLOCKED",
        [4] = "IBI_SIM_PIN_UNBL_BLOCKED",
        [5] = "IBI_SIM_PIN_VERIFIED",
    },
    ["IBISimRecordMode"] = {
        [2] = "IBI_SIM_NEXT_RECORD",
        [3] = "IBI_SIM_PREVIOUS_RECORD",
        [4] = "IBI_SIM_ABSOLUTE_MODE",
    },
    ["IBISimSecurityContext"] = {
        [0] = "IBI_SIM_SECURITY_CONTEXT_GSM",
        [1] = "IBI_SIM_SECURITY_CONTEXT_USIM_3G",
        [2] = "IBI_SIM_SECURITY_CONTEXT_USIM_GBA_BOOTSTRAP_MODE",
        [3] = "IBI_SIM_SECURITY_CONTEXT_USIM_GBA_NAF_DERIVATION_MODE",
        [4] = "IBI_SIM_SECURITY_CONTEXT_ISIM_IMS_AKA",
        [5] = "IBI_SIM_SECURITY_CONTEXT_ISIM_GBA_BOOTSTRAP_MODE",
        [6] = "IBI_SIM_SECURITY_CONTEXT_ISIM_GBA_NAF_DERIVATION_MODE",
        [7] = "IBI_SIM_SECURITY_CONTEXT_RESERVED",
    },
    ["IBISimSupportedTestCmdType"] = {
        [0] = "ICE_SIM_TEST_CMD_NULL",
        [1] = "ICE_SIM_TEST_CMD_WRITE_RPLMN",
        [2] = "ICE_SIM_TEST_CMD_READ_RPLMN",
        [3] = "ICE_SIM_TEST_CMD_CLEAR_FPLMN",
        [4] = "ICE_SIM_TEST_CMD_READ_CARD",
        [5] = "???",
        [6] = "ICE_SIM_TEST_CMD_MAX",
    },
    ["IBISimTkBcRepeatIndicator"] = {
        [0] = "IBI_SIM_TK_BC_REPEAT_INDICATOR_NO_REPEAT_INDICATOR",
        [1] = "???",
        [2] = "IBI_SIM_TK_BC_REPEAT_INDICATOR_CIRCULAR",
        [3] = "IBI_SIM_TK_BC_REPEAT_INDICATOR_FALLBACK",
        [4] = "IBI_SIM_TK_BC_REPEAT_INDICATOR_SCUD_IF",
    },
    ["IBISimTkCallControlParamType"] = {
        [0] = "IBI_SIM_TK_CALL_CONTROL_TYPE_ADDRESS",
        [1] = "IBI_SIM_TK_CALL_CONTROL_TYPE_SS_STRING",
        [2] = "IBI_SIM_TK_CALL_CONTROL_TYPE_USSD_STRING",
    },
    ["IBISimTkDurationUnit"] = {
        [0] = "IBI_SIM_TK_DURATION_UNIT_MINUTES",
        [1] = "IBI_SIM_TK_DURATION_UNIT_SECONDS",
        [2] = "IBI_SIM_TK_DURATION_UNIT_TENTH_OF_SECONDS",
    },
    ["IBISimTkProactiveCmdHandler"] = {
        [0] = "IBI_SIM_TK_CMD_HANDLER_UNCHANGED",
        [1] = "IBI_SIM_TK_CMD_HANDLER_MODEM",
        [2] = "IBI_SIM_TK_CMD_HANDLER_AP",
    },
    ["IBISimTkProvideLocalInfoType"] = {
        [3] = "IBI_SIM_TK_PROVIDE_LOCAL_INFO_TIME_ZONE",
        [4] = "IBI_SIM_TK_PROVIDE_LOCAL_INFO_LANGUAGE_SETTING",
    },
    ["IBISimTkTone"] = {
        [0] = "IBI_SIM_TK_TONE_DEFAULT_TONE",
        [1] = "IBI_SIM_TK_TONE_DIAL_TONE",
        [2] = "IBI_SIM_TK_TONE_CALLED_SUBSCRIBER_BUSY_TONE",
        [3] = "IBI_SIM_TK_TONE_CONGESTION_TONE",
        [4] = "IBI_SIM_TK_TONE_RADIO_PATH_ACK_TONE",
        [5] = "IBI_SIM_TK_TONE_RADIO_PATH_NOT_AVAIL_TONE",
        [6] = "IBI_SIM_TK_TONE_ERROR_TONE",
        [7] = "IBI_SIM_TK_TONE_CALL_WAITING_TONE",
        [8] = "IBI_SIM_TK_TONE_RINGING_TONE",
        [9] = "???",
        [10] = "???",
        [11] = "???",
        [12] = "???",
        [13] = "???",
        [14] = "???",
        [15] = "???",
        [16] = "IBI_SIM_TK_TONE_GENERAL_BEEP_TONE",
        [17] = "IBI_SIM_TK_TONE_POSITIVE_ACK_TONE",
        [18] = "IBI_SIM_TK_TONE_NEGATIVE_ACK_TONE",
        [19] = "IBI_SIM_TK_TONE_INCOMING_SPEECH_RING_TONE",
        [20] = "IBI_SIM_TK_TONE_INCOMING_SMS_RING_TONE",
    },
    ["IBISimUpdateStatus"] = {
        [0] = "IBI_SIM_SUCCESSFUL",
        [1] = "IBI_SIM_UNSUCCESSFUL",
        [2] = "IBI_SIM_MEM_RETRY_SUCCESS",
        [3] = "IBI_SIM_MEMORY_ERROR",
        [4] = "IBI_SIM_TOOLKIT_BUSY",
        [5] = "IBI_SIM_NO_EF_CHOOSEN",
        [6] = "IBI_SIM_INVALID_ADDRESS",
        [7] = "IBI_SIM_REFERENCE_ERROR",
        [8] = "IBI_SIM_INCONSISTENT_CMD",
        [9] = "IBI_SIM_NO_CHV_INITIALIZED",
        [10] = "IBI_SIM_SECURITY_ERROR",
        [11] = "IBI_SIM_CONTRADICT_WITH_CHV_STATE",
        [12] = "IBI_SIM_CONTRADICT_INVALID_STATE",
        [13] = "IBI_SIM_NO_ATTEMPT_LEFT",
        [14] = "IBI_SIM_MAX_VALUE_REACHED",
        [15] = "IBI_SIM_TOOLKIT_RESPONSE_ERROR",
        [16] = "IBI_SIM_APPLICATION_ERROR_P3",
        [17] = "IBI_SIM_APPLICATION_ERROR_P1P2",
        [18] = "IBI_SIM_UNKNOWN_INSTRUCTION",
        [19] = "IBI_SIM_WRONG_INSTRUCTION_CLASS",
        [20] = "IBI_SIM_TECHNICAL_PROBLEM",
        [21] = "IBI_SIM_APPLICATION_ERROR",
        [22] = "IBI_SIM_NOT_ACTIVATED",
        [23] = "IBI_SIM_MEMORY_EXCEEDED",
        [24] = "IBI_SIM_EXT_MEMORY_EXCEEDED",
        [25] = "IBI_SIM_CANNOT_REPLACE_SMS",
        [26] = "IBI_SIM_SUCCESS_BEYOND_END",
        [27] = "IBI_SIM_SUCCESS_INVALID_EXT",
        [28] = "IBI_SIM_MENU_SELECTING_CLIENT_CHANGED",
        [29] = "IBI_SIM_MENU_SELECTING_NO_NEXT_PROACTIVE",
    },
    ["IBISipCallDirection"] = {
        [0] = "IBI_SIP_CALL_DIRECTION_NA",
        [1] = "IBI_SIP_CALL_DIRECTION_INCOMING",
        [2] = "IBI_SIP_CALL_DIRECTION_OUTGOING",
    },
    ["IBISipMsgId"] = {
        [0] = "IBI_SIP_MSG_NA",
        [1] = "IBI_SIP_MSG_REGISTER",
        [2] = "IBI_SIP_MSG_INVITE",
        [3] = "IBI_SIP_MSG_PRACK",
        [4] = "IBI_SIP_MSG_CANCEL",
        [5] = "IBI_SIP_MSG_ACK",
        [6] = "IBI_SIP_MSG_BYE",
        [7] = "IBI_SIP_MSG_SUBSCRIBE",
        [8] = "IBI_SIP_MSG_NOTIFY",
        [9] = "IBI_SIP_MSG_UPDATE",
        [10] = "IBI_SIP_MSG_REFER",
        [11] = "IBI_SIP_MSG_MESSAGE",
        [12] = "IBI_SIP_MSG_INFO",
        [13] = "IBI_SIP_MSG_PUBLISH",
        [14] = "IBI_SIP_MSG_OPTIONS",
    },
    ["IBISmsCheckBitmask"] = {
        [1] = "IBI_SMS_CHECK_DISABLE_ALL",
        [2] = "IBI_SMS_CHECK_SCA",
        [3] = "???",
        [4] = "IBI_SMS_CHECK_DA",
        [5] = "???",
        [6] = "???",
        [7] = "???",
        [8] = "IBI_SMS_CHECK_TP_MR",
    },
    ["IBISmsCpResult"] = {
        [0] = "IBI_SMS_CP_ACK",
        [1] = "IBI_SMS_CP_ERROR",
        [2] = "IBI_SMS_MN_TIMEOUT",
        [3] = "IBI_SMS_CM_RELEASE",
    },
    ["IBISmsMsgWaitInd"] = {
        [0] = "IBI_SMS_MSG_WAIT_SET_UNKNOWN",
        [1] = "IBI_SMS_MSG_WAIT_SET_INACTIVE",
        [2] = "IBI_SMS_MSG_WAIT_SET_ACTIVE",
    },
    ["IBISmsMsgWaitType"] = {
        [0] = "IBI_SMS_MSG_WAIT_VOICE_MAIL",
        [1] = "IBI_SMS_MSG_WAIT_MAX",
    },
    ["IBISmsPpProtocol"] = {
        [0] = "IBI_SMS_REPLACE_TYPE",
        [1] = "IBI_SMS_PP_DOWNLOAD",
        [2] = "IBI_SMS_PP_NORMAL",
        [3] = "IBI_SMS_ME_DOWNLOAD",
        [4] = "IBI_SMS_PP_DEPERSONALIZE",
        [5] = "IBI_SMS_PP_TYPE0",
        [6] = "IBI_SMS_PP_ANSI_136_R_DATA",
    },
    ["IBISmsSendMoreMessagesStatus"] = {
        [0] = "IBI_SMS_SEND_MORE_MESSAGES_STATUS_DISABLE",
        [1] = "IBI_SMS_SEND_MORE_MESSAGES_STATUS_ENABLE_ONCE",
        [2] = "IBI_SMS_SEND_MORE_MESSAGES_STATUS_ENABLE_PERMANENTLY",
    },
    ["IBISmsServiceErrorCause"] = {
        [0] = "IBI_SMS_ERROR_CAUSE_NONE",
        [1] = "IBI_SMS_ERROR_CAUSE_SMSC_ADDRESS_NOT_PRESENT",
        [2] = "IBI_SMS_ERROR_CAUSE_SMS_SERVICE_NOT_AVAILABLE",
    },
    ["IBISsAddressType"] = {
        [0] = "IBI_SS_ADDRESS_TYPE_PHONE_NUMBER",
    },
    ["IBISsClirOption"] = {
        [0] = "IBI_SS_CLIR_OPT_PERMANENT",
        [1] = "IBI_SS_CLIR_OPT_TEMPORARY_DEFAULT_RESTRICTED",
        [2] = "IBI_SS_CLIR_OPT_TEMPORARY_DEFAULT_ALLOWED",
        [3] = "IBI_SS_CLIR_OPT_VOID_CLI_RESTRICTION",
    },
    ["IBISsLcsFormatInd"] = {
        [0] = "IBI_SS_LCS_FORMAT_IND_LOGICAL_NAME",
        [1] = "IBI_SS_LCS_FORMAT_IND_EMAIL_ADDRESS",
        [2] = "IBI_SS_LCS_FORMAT_IND_MSISDN",
        [3] = "IBI_SS_LCS_FORMAT_IND_URL",
        [4] = "IBI_SS_LCS_FORMAT_IND_SIPURL",
        [5] = "IBI_SS_LCS_FORMAT_IND_IMS_PUBLIC_ID",
    },
    ["IBISsLcsGanssId"] = {
        [0] = "IBI_SS_LCS_GANSS_ID_GALILEO",
        [1] = "IBI_SS_LCS_GANSS_ID_SBAS",
        [2] = "IBI_SS_LCS_GANSS_ID_MOD_GPS",
        [3] = "IBI_SS_LCS_GANSS_ID_QZSS",
        [4] = "IBI_SS_LCS_GANSS_ID_GLONASS",
        [5] = "IBI_SS_LCS_GANSS_ID_BDS",
    },
    ["IBISsLcsLocEstimateType"] = {
        [0] = "IBI_SS_LCS_LOC_ESTIMATE_TYPE_CURRENT_LOCATION",
        [1] = "IBI_SS_LCS_LOC_ESTIMATE_TYPE_CURRENT_OR_LAST_KNOWN_LOCATION",
        [2] = "IBI_SS_LCS_LOC_ESTIMATE_TYPE_INITIAL_LOCATION",
        [3] = "IBI_SS_LCS_LOC_ESTIMATE_TYPE_ACTIVATE_DEFERRED_LOC",
        [4] = "IBI_SS_LCS_LOC_ESTIMATE_TYPE_CANCEL_DEFERRED_LOC",
        [5] = "IBI_SS_LCS_LOC_ESTIMATE_TYPE_NOTIFY_VERIFY_ONLY",
        [6] = "IBI_SS_LCS_LOC_ESTIMATE_TYPE_INVALID",
    },
    ["IBISsLcsNotifyType"] = {
        [0] = "IBI_SS_LCS_NOTIFY_TYPE_LOC_ALLOWED",
        [1] = "IBI_SS_LCS_NOTIFY_TYPE_VERIFY_LOC_ALLOWED_IF_NO_RSP",
        [2] = "IBI_SS_LCS_NOTIFY_TYPE_VERIFY_LOC_NOT_ALLOWED_IF_NO_RSP",
    },
    ["IBISsLcsOperationType"] = {
        [0] = "IBI_SS_LCS_OPERATION_TYPE_SET",
        [1] = "IBI_SS_LCS_OPERATION_TYPE_GET",
    },
    ["IBISsLcsVerifyRspType"] = {
        [1] = "IBI_SS_LCS_VERIFY_RSP_TYPE_GRANTED",
        [0] = "IBI_SS_LCS_VERIFY_RSP_TYPE_DENIED",
    },
    ["IBISsNetworkRejectCause"] = {
        [0] = "IBI_SS_NET_REJECT_UNRECOGNIZED_COMPONENT",
        [1] = "IBI_SS_NET_REJECT_MISTYPED_COMPONENT",
        [2] = "IBI_SS_NET_REJECT_BADLY_STRUCTURED_COMPONENT",
        [3] = "IBI_SS_NET_REJECT_DUPLICATE_INVOKE_ID",
        [4] = "IBI_SS_NET_REJECT_UNRECOGNIZED_OPERATION",
        [5] = "IBI_SS_NET_REJECT_MISTYPED_PRO_PARAMETER",
        [6] = "IBI_SS_NET_REJECT_RESOURCE_LIMITATION",
        [7] = "IBI_SS_NET_REJECT_INITIATING_RELEASE",
        [8] = "IBI_SS_NET_REJECT_UNRECOGNIZED_LINKED_ID",
        [9] = "IBI_SS_NET_REJECT_LINKED_RESPONSE_UNEXPECTED",
        [10] = "IBI_SS_NET_REJECT_UNEXPECTED_LINKED_OPERATION",
        [11] = "IBI_SS_NET_REJECT_UNRECOGNIZED_INVOKE_ID",
        [12] = "IBI_SS_NET_REJECT_RETURN_RESULT_UNEXPECTED",
        [13] = "IBI_SS_NET_REJECT_MISTYPED_RES_PARAMETER",
        [14] = "IBI_SS_NET_REJECT_UNRECOGNIZED_ERROR_INVOKE_ID",
        [15] = "IBI_SS_NET_REJECT_RETURN_ERROR_UNEXPECTED",
        [16] = "IBI_SS_NET_REJECT_UNRECOGNIZED_ERROR",
        [17] = "IBI_SS_NET_REJECT_UNEXPECTED_ERROR",
        [18] = "IBI_SS_NET_REJECT_MISTYPED_ERROR_PARAMETER",
        [19] = "IBI_SS_NET_REJECT_IMS_NETWORK_ERROR",
        [20] = "IBI_SS_NET_REJECT_UNKNOWN",
    },
    ["IBISsOperationCode"] = {
        [0] = "IBI_SS_OC_ACTIVATION",
        [1] = "IBI_SS_OC_DEACTIVATION",
        [2] = "IBI_SS_OC_REGISTRATION",
        [3] = "IBI_SS_OC_DEREGISTRATION",
        [4] = "IBI_SS_OC_INTERROGATION",
        [5] = "IBI_SS_OC_CHANGE_PASSWORD",
        [6] = "IBI_SS_OC_GET_PASSWORD",
        [7] = "IBI_SS_OC_MO_USSD_DATA",
        [8] = "IBI_SS_OC_MO_USSD_REQ",
        [9] = "IBI_SS_OC_NW_USSD_NTF",
        [10] = "IBI_SS_OC_NW_USSD_REQ",
        [11] = "IBI_SS_OC_UNKNOWN",
    },
    ["IBISsOperationResult"] = {
        [0] = "IBI_SS_OPERATION_SUCCESSFUL",
        [1] = "IBI_SS_OPERATION_NW_ERROR",
        [2] = "IBI_SS_OPERATION_ERROR_ON_RELEASE_COMPLETE",
        [3] = "IBI_SS_OPERATION_NW_REJECT",
    },
    ["IBISsServiceCode"] = {
        [0] = "IBI_SS_SV_CODE_CF_UNCONDITIONAL",
        [1] = "IBI_SS_SV_CODE_CF_BUSY",
        [2] = "IBI_SS_SV_CODE_CF_NO_REPLY",
        [3] = "IBI_SS_SV_CODE_CF_NOT_REACHABLE",
        [4] = "IBI_SS_SV_CODE_CF_ALL",
        [5] = "IBI_SS_SV_CODE_CF_ALL_COND",
        [6] = "IBI_SS_SV_CODE_CB_BAOC",
        [7] = "IBI_SS_SV_CODE_CB_BOIC",
        [8] = "IBI_SS_SV_CODE_CB_BOIC_EX_HC",
        [9] = "IBI_SS_SV_CODE_CB_BAIC",
        [10] = "IBI_SS_SV_CODE_CB_BIC_ROAM",
        [11] = "IBI_SS_SV_CODE_CB_ALL_BARRING_SERVICES",
        [12] = "IBI_SS_SV_CODE_CB_ALL_OUTGOING_BARRING_SERVICES",
        [13] = "IBI_SS_SV_CODE_CB_ALL_INCOMING_BARRING_SERVICES",
        [14] = "IBI_SS_SV_CODE_CALL_WAITING",
        [15] = "IBI_SS_SV_CODE_CLIR",
        [16] = "IBI_SS_SV_CODE_CLIP",
        [17] = "IBI_SS_SV_CODE_COLR",
        [18] = "IBI_SS_SV_CODE_COLP",
        [19] = "IBI_SS_SV_CODE_CNAP",
        [20] = "IBI_SS_SV_CODE_USSD",
        [21] = "IBI_SS_SV_CODE_UNKOWN",
    },
    ["IBISsStatusCode"] = {
        [1] = "IBI_SS_STATUS_CODE_ACTIVATION",
        [2] = "IBI_SS_STATUS_CODE_REGISTRATION",
        [3] = "???",
        [4] = "IBI_SS_STATUS_CODE_PROVISION",
        [5] = "???",
        [6] = "???",
        [7] = "???",
        [8] = "IBI_SS_STATUS_CODE_QUIESCENT",
    },
    ["IBISsUssdSendMode"] = {
        [0] = "IBI_SS_USSD_MMI_MODE",
        [1] = "IBI_SS_USSD_APP_USSD_MODE",
        [2] = "IBI_SS_USSD_APP_SS_MODE",
    },
    ["IBISsUssdType"] = {
        [0] = "IBI_SS_USSD_IT_MO_DATA",
        [1] = "IBI_SS_USSD_IT_MO_REQUEST",
        [2] = "IBI_SS_USSD_IT_NO_NOTIFY",
        [3] = "IBI_SS_USSD_IT_NO_REQUEST",
    },
    ["IBIVinylResult"] = {
        [0] = "VINYL_RESULT_SUCCESS",
        [1] = "VINYL_RESULT_FAILURE",
        [2] = "VINYL_RESULT_SIM_NOT_READY",
        [3] = "VINYL_RESULT_INVALID_SLOT",
        [4] = "VINYL_RESULT_NO_SIM",
        [5] = "VINYL_RESULT_INVALID_PARAM",
        [6] = "VINYL_RESULT_OPER_NOT_SUPPORTED",
        [7] = "VINYL_RESULT_NOT_ACTIVATED",
    },
    ["IBIVinylSupport"] = {
        [0] = "IBI_VINYL_SUPPORT_UNKNOWN",
        [1] = "IBI_VINYL_SUPPORT_NONE",
        [2] = "IBI_VINYL_SUPPORT_TAPE",
    },
    ["IBIVinylTapeCmd"] = {
        [0] = "IBI_VINYL_TAPE_CMD_GET_EUICC_CONFIGURED_ADDRESS",
        [1] = "IBI_VINYL_TAPE_CMD_SET_DEFAULT_DP_ADDRESS",
        [2] = "IBI_VINYL_TAPE_CMD_GET_EUICC_CHALLENGE",
        [3] = "IBI_VINYL_TAPE_CMD_GET_EUICC_INFO",
        [4] = "IBI_VINYL_TAPE_CMD_PREPARE_DOWNLOAD",
        [5] = "IBI_VINYL_TAPE_CMD_LOAD_BOUND_PROFILE_PACKAGE",
        [6] = "IBI_VINYL_TAPE_CMD_LIST_NOTIFICATIONS",
        [7] = "IBI_VINYL_TAPE_CMD_RETRIEVE_NOTIFICATIONS_LIST",
        [8] = "IBI_VINYL_TAPE_CMD_REMOVE_NOTIFICATION_FROM_LIST",
        [9] = "IBI_VINYL_TAPE_CMD_LOAD_CRL",
        [10] = "IBI_VINYL_TAPE_CMD_AUTHENTICATE_SERVER",
        [11] = "IBI_VINYL_TAPE_CMD_CANCEL_SESSION",
        [12] = "IBI_VINYL_TAPE_CMD_GET_RAT",
        [13] = "IBI_VINYL_TAPE_CMD_GET_PROFILES_INFO",
        [14] = "IBI_VINYL_TAPE_CMD_ENABLE_PROFILE",
        [15] = "IBI_VINYL_TAPE_CMD_DISABLE_PROFILE",
        [16] = "IBI_VINYL_TAPE_CMD_DELETE_PROFILE",
        [17] = "IBI_VINYL_TAPE_CMD_EUICC_MEMORY_RESET",
        [18] = "IBI_VINYL_TAPE_CMD_GET_EID",
        [19] = "IBI_VINYL_TAPE_CMD_SET_NICKNAME",
        [20] = "IBI_VINYL_TAPE_CMD_GET_SESSION_DATA",
        [21] = "IBI_VINYL_TAPE_CMD_CLEAR_SESSION_DATA",
    },
    ["IBIXccClockControlIndType"] = {
        [0] = "IBI_XCC_IND_TYPE_XO_SYNC_STATUS",
        [1] = "IBI_XCC_IND_TYPE_CLOCK_TIMEOUT",
        [2] = "IBI_XCC_IND_TYPE_INVALID",
    },
    ["IBIXccClockControlRspType"] = {
        [0] = "IBI_XCC_RSP_TYPE_XO_SYNC_STATUS",
        [1] = "IBI_XCC_RSP_TYPE_CLOCK_TIMEOUT",
        [2] = "IBI_XCC_RSP_TYPE_INVALID",
        [3] = "IBI_XCC_RSP_TYPE_SUCCESS",
    },
    ["IBIXccLtlIndType"] = {
        [0] = "IBI_LTL_XCC_IND_TYPE_SUCCESS",
        [1] = "IBI_LTL_XCC_IND_TYPE_NOT_SUPPORTED",
        [2] = "IBI_LTL_XCC_IND_TYPE_INVALID_PARAM",
        [3] = "IBI_LTL_XCC_IND_TYPE_INVALID",
    },
    ["IBIXccLtlInfoType"] = {
        [-1] = "IBI_XCC_LTL_INFO_TYPE_INVALID",
        [0] = "IBI_XCC_LTL_INFO_TYPE_INITIAL",
        [1] = "IBI_XCC_LTL_INFO_TYPE_LTL_REFITTED_LUT",
        [2] = "IBI_XCC_LTL_INFO_TYPE_LEARNT_ARRAY",
    },
    ["IBIXccPeripheral"] = {
        [0] = "IBI_XCC_PERIPHERAL_GNSS",
    },
    ["IBIXoConnectedMode"] = {
        [0] = "IBI_XO_MODE_INVALID",
        [1] = "IBI_XO_MODE_IDLE",
        [2] = "IBI_XO_MODE_CONNECTED",
    },
    ["IBIXoState"] = {
        [-1] = "IBI_XO_STATE_INVALID",
        [0] = "IBI_XO_STATE_GSM",
        [1] = "IBI_XO_STATE_UMTS",
        [2] = "IBI_XO_STATE_LTE",
        [3] = "IBI_XO_STATE_TD_SCDMA",
    },
    ["AriResult_enum"] = {
        [-100] = "IBI_ERROR_SPECIFIC",
        [-99] = "???",
        [-98] = "???",
        [-97] = "???",
        [-96] = "???",
        [-95] = "???",
        [-94] = "???",
        [-93] = "???",
        [-92] = "ARI_TRANSPORT_FAILURE_E",
        [-91] = "ARI_RT_CONNECTION_FAILURE_E",
        [-90] = "ARI_RT_WRONG_STATE_E",
        [-89] = "ARI_RT_NOT_HANDLED_E",
        [-88] = "ARI_MSG_NOT_AUTHORIZED_E",
        [-87] = "ARI_TOO_MANY_REQS_E",
        [-86] = "ARI_GROUP_NOT_RDY_E",
        [-85] = "ARI_BBFW_RESET_E",
        [-84] = "ARI_MSG_TIMEOUT_E",
        [-83] = "ARI_TLV_WRONG_SIZE_E",
        [-82] = "ARI_NO_MORE_MEMORY_E",
        [-81] = "ARI_MANDATORY_TLV_MISSING_E",
        [-80] = "ARI_TLV_TOO_LARGE_E",
        [-79] = "ARI_UNPACK_INVALID_BUFF_E",
        [-78] = "ARI_UNPACK_UNKNOWN_TLV_E",
        [-77] = "ARI_PACK_DUP_TLV_E",
        [-76] = "ARI_PACK_UNKNOWN_TLV_E",
        [-75] = "ARI_PACK_INVALID_VALUE_E",
        [-74] = "ARI_INVALID_MSG_BUFF_E",
        [-73] = "ARI_VALIDATE_WRONG_MSGID_E",
        [-72] = "ARI_MSG_PARAM_INIT_FAILED_E",
        [-71] = "ARI_MSG_NOT_PRESENT_E",
        [-70] = "ARI_GROUP_NOT_PRESENT_E",
        [-69] = "ARI_WEAK_IMPL_INVOKED_E",
        [-68] = "???",
        [-67] = "???",
        [-66] = "???",
        [-65] = "???",
        [-64] = "???",
        [-63] = "???",
        [-62] = "???",
        [-61] = "???",
        [-60] = "???",
        [-59] = "???",
        [-58] = "???",
        [-57] = "???",
        [-56] = "???",
        [-55] = "???",
        [-54] = "???",
        [-53] = "???",
        [-52] = "???",
        [-51] = "???",
        [-50] = "???",
        [-49] = "???",
        [-48] = "???",
        [-47] = "???",
        [-46] = "???",
        [-45] = "???",
        [-44] = "???",
        [-43] = "???",
        [-42] = "???",
        [-41] = "???",
        [-40] = "???",
        [-39] = "???",
        [-38] = "???",
        [-37] = "???",
        [-36] = "???",
        [-35] = "???",
        [-34] = "???",
        [-33] = "???",
        [-32] = "???",
        [-31] = "???",
        [-30] = "???",
        [-29] = "???",
        [-28] = "???",
        [-27] = "???",
        [-26] = "???",
        [-25] = "???",
        [-24] = "???",
        [-23] = "???",
        [-22] = "???",
        [-21] = "???",
        [-20] = "???",
        [-19] = "???",
        [-18] = "???",
        [-17] = "???",
        [-16] = "???",
        [-15] = "IBI_ERROR_STORAGE_ACCESS_FAILURE",
        [-14] = "IBI_ERROR_OPERATION_PENDING",
        [-13] = "IBI_ERROR_OUT_OF_HANDLES",
        [-12] = "IBI_ERROR_IO_ERROR",
        [-11] = "IBI_ERROR_INSUFFICIENT_PERMISSIONS",
        [-10] = "IBI_ERROR_BAD_FORMAT",
        [-9] = "IBI_ERROR_WRONG_STATE",
        [-8] = "IBI_ERROR_TIMEOUT",
        [-7] = "IBI_ERROR_NOT_SUPPORTED",
        [-6] = "IBI_ERROR_TOO_SMALL_BUF_PARAM",
        [-5] = "IBI_ERROR_INVALID_PARAM",
        [-4] = "IBI_ERROR_OUT_OF_RANGE_PARAM",
        [-3] = "IBI_ERROR_INVALID_HANDLE",
        [-2] = "IBI_ERROR_OUT_OF_MEMORY",
        [-1] = "ARI_RESULT_ERR_E",
        [0] = "ARI_RESULT_OK_E",
    },
    ["AriAttribType"] = {
        [2] = "ARI_ATTR_INDICATION",
        [3] = "ARI_ATTR_WAKE_AP",
        [4] = "UNKNOWN",
        [5] = "ARI_ATTR_LPM",
        [6] = "ARI_ATTR_LPM_COMMIT",
    },
    ["AriAttribActionType"] = {
        [2] = "ARI_ATTR_GET",
        [1] = "ARI_ATTR_SET",
    },
    ["OpState"] = {
        [-1] = "Ari::UNINITIALIZED",
        [0] = "UNKNOWN",
        [1] = "Ari::INITIALIZED",
        [2] = "Ari::RT_RUNNING",
        [3] = "Ari::RT_AP_LPM",
        [4] = "Ari::RT_STOPPED",
    },
    ["AriAttribValue"] = {
        [0] = "ARI_ATTR_OFF",
        [2147483647] = "ARI_ATTR_ON",
    },
    ["ARI_XPC_NOTIFY_IDS"] = {
        [0] = "INVALID",
        [1] = "ALL_READY",
        [2] = "STALL4CRASH",
        [3] = "LPM_ENTER",
        [4] = "LPM_EXIT",
        [5] = "STALL4LPM",
        [6] = "DEPRECATED_0",
        [7] = "DUMP_STATE",
        [8] = "END_CANCEL",
    },
}
